### ISSUE TITLE
Serial Number from Discovery

### ISSUE THREAD

**Issue by andrioid** [tr3v3r/react-native-esc-pos-printer#1]
I was trying to integrate the Epson SDK to our Android POS system when I found your package and thought it would be smarter to contribute to yours than to build my own.

Is there any way to get the serial number from Discovery? There is a method called `Printer.getPrinterInformation`, but as far as I can tell, I need to connect to the printer first. The sample programs from Epson don't use this method at all.

The use-case is that we are auto-detecting printers across the network and we need to be be able to pick and identify them. IP addresses or USB ports can change, but the serial-number remains the same.

I'd be happy contribute any changes that we make to your library.

**Comment by tr3v3r** [comment]
Hi @andrioid.

According to docs, there is no way to get serial numbers within the discovery method.

![image](https://user-images.githubusercontent.com/23724142/111022198-5e20fd80-83e2-11eb-8c22-f19346c0c704.png)
![image](https://user-images.githubusercontent.com/23724142/111022214-755feb00-83e2-11eb-957f-1b0e2fd295b5.png)

Why don't you show the device name instead of the serial number?

We can add this method, but according to this table, not all printer series support it

![image](https://user-images.githubusercontent.com/23724142/111022283-dab3dc00-83e2-11eb-8fd6-d81415587cba.png)

**Comment by tr3v3r** [comment]
It seems that the only way, for now, is to discover. 
After the search finished try to get serial numbers using loop
```javascript
search.results.forEach(async printer => {
  const { target, name } = printer;

  await EscPosPrinter.init({
    target: target,
    seriesName: getPrinterSeriesByName(name),
  });
  
  const info = await EscPosPrinter.getPrinterInfo();
  
  console.log(info) /*
  {
"PrinterSpec": {
"Product": {
"SerialNo": "ABC1234567"
} },
"Maintenance": { "ThermalHead": {
"NumberOfWarningDot": "0", "PositionOfWarningDot": "", "NumberOfBrokenDot": "0", "PositionOfBrokenDot": ""
} }
}
  
  */
  
  })
  ```
  
  If you OK with this approach and limitations ( regarding printer series ) I'll add this method asap

**Comment by andrioid** [comment]
Ok. Hang tight. I asked our Java dude to take a look and he might have a PR soon

**Comment by tr3v3r** [comment]
@andrioid OK then keep me posted and I'll add corresponding logic for iOS as well

**Comment by tr3v3r** [comment]
@andrioid Just released new version 0.13.4 with [latest updatets](https://github.com/tr3v3r/react-native-esc-pos-printer/pull/3) included.

**Comment by fragilehm** [comment]
> Hi @andrioid.
> 
> According to docs, there is no way to get serial numbers within the discovery method.
> 
> ![image](https://user-images.githubusercontent.com/23724142/111022198-5e20fd80-83e2-11eb-8c22-f19346c0c704.png) ![image](https://user-images.githubusercontent.com/23724142/111022214-755feb00-83e2-11eb-957f-1b0e2fd295b5.png)
> 
> Why don't you show the device name instead of the serial number?
> 
> We can add this method, but according to this table, not all printer series support it
> 
> ![image](https://user-images.githubusercontent.com/23724142/111022283-dab3dc00-83e2-11eb-8fd6-d81415587cba.png)

Hi, @tr3v3r first of all thanks for maintaining this package. I was looking online for this documentation but could find it, can you please send the link or pdf?

**Comment by tr3v3r** [comment]
@fragilehm Hi!
Could you please check [this link](https://download.epson-biz.com/modules/pos/index.php?page=single_soft&cid=6737&scat=61&pcat=52)?

You need to download this zip. 
![image](https://user-images.githubusercontent.com/23724142/141291590-791780a5-de77-4b9c-aad8-61746e4ee06d.png)

Inside you can find user manual with corresponding information about API.

**Comment by duxthefux** [comment]
@andrioid were you able to obtain the serial number of printer? 

I'm currently trying to accomplish it, but also receive error code `33` which means `device is busy` although it isn't.

```swift
 device = Epos2Printer(printerSeries: EPOS2_TM_P20.rawValue, lang: EPOS2_MODEL_ANK.rawValue)

/** Connecting to the discovered device */
let result = device!.connect("TCP:192.168.178.61", timeout: 15_000)
guard result == EPOS2_SUCCESS.rawValue else {
    Log.e("Epson", "Couldn't connect to device. Code: \(result)")
    return
}
Log.i("Epson", "Connected to device. Next step will be to retrieve printer information for ...")

device!.getInformation(15_000, delegate: self)
```


The delegate function looks like
```swift
func onGetPrinterInformation(_ code: Int32, jsonString: String!) {
    Log.i("Epson", "Information found (Code \(code)) for the discovered printer: \(String(describing: jsonString)). ")
}
```

Received log message from it is:
```log
Information found (Code 33) for the discovered printer: Optional("{\"Maintenance\":{\"ThermalHead\":{\"PositionOfBrokenDot\":\"\",\"NumberOfBrokenDot\":\"\",\"NumberOfWarningDot\":\"\",\"PositionOfWarningDot\":\"\"}},\"PrinterSpec\":{\"Product\":{\"SerialNo\":\"\"}}}"). 
```
I tried to find some examples or existing code snippets, but didn't find anything related to calling `getInformation` (former `getPrinterInformation`) and after days, now getting kinda frustrated and hope you managed to do it and can a provide working example.

Thanks a lot for your help!
