### ISSUE TITLE
Android ERR_TYPE_INVALID when printing on TM-L90

### ISSUE THREAD

**Issue by nullfox** [tr3v3r/react-native-esc-pos-printer#100]
I was able to discover my Epson TM-L90 when connected to a Samsung tablet via USB.

Whenever I attempt to print a label, the promise rejects with `Error: ERR_TYPE_INVALID` - From what I can see from the library, this is just passing that error from the Epson Android SDK to your project. I realize it may be impossible to debug but I'm curious if you've seen this before?

Sample code:
```
await printing
          .initialize()
          .text('Hello World')
          .send();
```

For reference, the library correctly identifies the printer and series as:
Name: `TM-L90`
Series: `EPOS2_TM_L90`

**Comment by tr3v3r** [comment]
@nullfox Hello. 
Sorry I have only LAN printer and can't help with debugging (
But previously I didn't have such issues for our app that uses this lib.  We had there all types of connections like LAN, WIFI, BLE, USB

What method do you use to init printer? **init** or **instantiate** ?


If you're going to debug you can try to find a bit more info about errors here

https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/android_v2.23.0.pdf

**Comment by nullfox** [comment]
Hi @tr3v3r 

Thank you for the reply! Luckily, I got it working!

Changing the `seriesName` param from being `getPrinterSeriesByName(printer.name)` which returned `EPOS_TM_L90` I looked through the `PrinterSeriesName` type and found another one called `EPOS2_TM_L90LFC`. Hardcoding that value into `seriesName` fixes the issue and printing is working!

Cheers

**Comment by tr3v3r** [comment]
@nullfox So for some reason, the wrong name was used?
Could you please tell me what is the **printer.name** value?

**Comment by joanEstrada** [comment]
I had the same issue, I solved it with a simple rebuild.
