### ISSUE TITLE
Don't receive print errors after printer instantiation

### ISSUE THREAD

**Issue by chahinramonaghrim** [tr3v3r/react-native-esc-pos-printer#101]
I have multiple printers that I am printing on. Once I instantiate a printer and successfully print on it, I don't receive print errors when e.g the printers goes off or when the printer has no paper anymore. I keep getting 'PRINT_SUCCESS' when sending payloads to the printer even tho its offline or has no paper anymore. Only when I restart my app, it shows me the error. This is what I do: 

1. Turn on Printer and discover printer:
` EscPosPrinter.discover({ usbSerialNumber: true });`

2. Instantiate printer:
`EscPosPrinter.instantiate({
      target: printer.target,
      seriesName: getPrinterSeriesByName(printer.name),
      language: "EPOS2_LANG_EN",
    })`

3. Create print payload  
`new EscPosPrinter.printing().initialize().text('Hello).send({
          target: printer.target
   });`

4. Print success:

5. Turn off printer:

6. Create print payload and send it to offline printer:
`new EscPosPrinter.printing().initialize().text('Hello).send({
          target: printer.target
   });`

7. Print Success

I dont understand why I do not receive upon the 7th step an error because the printer is offline. Please need help.

**Comment by tr3v3r** [comment]
@chahinramonaghrim  Hello!
Could you please do the same test using [init](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/API.md#init-target-seriesname-language-) method instead? 

I mean the case with turned-off the printer?

**Comment by chahinramonaghrim** [comment]
@tr3v3r I did that and it is the same behaviour. I only get the error response once I kill my app and try to follow the same steps that I described above. Any other idea why it is not working for me? I am working with two Epson printers TM-T20|||

**Comment by chahinramonaghrim** [comment]
@tr3v3r I also imported the MultiPrintModal that you created in the example folder and with this I also didnt receive any error once I have instantiate or inited a printer. There must be something wrong I believe.

**Comment by chahinramonaghrim** [comment]
Hello any update?

**Comment by FawzyMokhtar** [comment]
Does this package supports printing on printers other than TM Printers?
E.g. XPrinter.

**Comment by tolypash** [comment]
@tr3v3r I am experiencing the same issue here. If I instantiate printer, and then send print job all works fine. Then I open the cover, and send the same print job, and it still responds with success.

When I was using `init` however, it was throwing an error successfully. Any ideas how to work around this? :)

**Comment by tr3v3r** [comment]
Instantiate is deprecated. Use latest lib version
