### ISSUE TITLE
new NativeEventEmitter() requires a non null argumen

### ISSUE THREAD

**Issue by AlbertJohanson** [tr3v3r/react-native-esc-pos-printer#107]
Im getting the next error: 
![344276980_572246221557537_2596505567166089110_n](https://user-images.githubusercontent.com/56742261/236728328-b0cd3213-cd95-4fd9-a03f-be78e8112585.jpg)

does anyone had a solution i follow the steps but i dont find the ansewer to resolve this bug

**Comment by tr3v3r** [comment]
@AlbertJohanson  Can I ask you to give me a bit more details?

**Comment by AlbertJohanson** [comment]
Sure! when i call the module in a component for my app and i call any of the method in the API throws me that error.

**Comment by AlbertJohanson** [comment]
@tr3v3r 
Sure! when i call the module in a component for my app and i call any of the method in the API throws me that error.

**Comment by tr3v3r** [comment]
@AlbertJohanson By details I mean RN and lib version. bare or expo projects . Android or iOS and etc.

**Comment by Hyperman012** [comment]
I see this error in Android - RN version 71, lib version 2.5.1

**Comment by mahendra-t-guardhat** [comment]
+1

**Comment by YasinAkimura** [comment]
I'm facing the same issue on Android SDK version 33, RN version 0.72.6, lib version 2.6.0. 
Mostly I could ignore the warning but I'm facing issues like wrong return types and printer not being able to print on release after a few minutes screen off.
