### ISSUE TITLE
Can we use MAC address instead of IP?

### ISSUE THREAD

**Issue by rafaelmonroy** [tr3v3r/react-native-esc-pos-printer#109]
Is it possible to init a printer by passing a MAC address instead of IP to the target value? I see that MAC address is a supported identifier in the official epson epos sdk documentation, but not seeing it mentioned here. 

Thank you

**Comment by tr3v3r** [comment]
Hi @rafaelmonroy 
<img width="1110" alt="image" src="https://github.com/tr3v3r/react-native-esc-pos-printer/assets/23724142/6bddd629-2783-4311-bed5-096efe50dbad">
