### ISSUE TITLE
TM-P80 not discoverable (BT)  on Android 10

### ISSUE THREAD

**Issue by brianjd** [tr3v3r/react-native-esc-pos-printer#110]
I have a TM-P80 and an Android 10 device.  I have confirmed the necessary permissions etc.  But BT discovery always returns an empty array.  I have experimented with increasing the discovery timeout with no luck.  The printer works fine with an iOS device I have running the same app.  Any suggestions?

**Comment by zain-saffi** [comment]
@brianjd Greetings,
Were you able to solve this? I am currently facing same issue.

**Comment by brianjd** [comment]
@zain-saffi My problem had to do with how iOS handles BT devices.  Since the iOS device had to be paired, it prevented the printer from being discovered by other devices.  Removing the iOS pairing made the printer discoverable across multiple Android devices. 🥴
