### ISSUE TITLE
[QUESTION] Multiple printers

### ISSUE THREAD

**Issue by nguyen-vo** [tr3v3r/react-native-esc-pos-printer#12]
Hi, does the package support multiple printers? I see in the document that we have to use the init function before we print. So if I have multiple printers is it safe to use that function multiple times? In my application, I have a list of printers with IP addresses and mac addresses. Every time we execute our print function, then it loops through the printer list, connects with a printer, and then prints.

**Comment by tr3v3r** [comment]
Hi! 


Init function is just set the current printer to work with. So you can safely re-init printers and print in a sequence. The only thing you need to do is just wait until the current printer finishes its work and then run the next one



```
await EscPosPrinter.init({
  target: 'first printer target', 
})

await printing
  .initialize()
  .line('DUDE!')
  .send()
  
await EscPosPrinter.init({
  target: 'another printer target', 
})

```

The solution is not ideal but should work.

Hope it helps

**Comment by nguyen-vo** [comment]
@tr3v3r Oh okay thank you :D
