### ISSUE TITLE
getPrinterCharsPerLine(seriesName) Error

### ISSUE THREAD

**Issue by manny-cuboh** [tr3v3r/react-native-esc-pos-printer#121]
Hoping I'm just missing something simple but I am unable to use `getPrinterCharsPerLine` without it throwing a `[Error: ERR_PARAM]`. 

I have tried it with multiple printer series ie. EPOS2_TM_M30, EPOS2_TM_T88, and EPOS2_TM_U220. All 3 come back with the same Error. 

I also tried to use the `instantiate` as well as `init` before calling the function but this also resulted in the same error being thrown. 

Im using it exactly as it shows in the docs ```await EscPosPrinter.getPrinterCharsPerLine(getPrinterSeriesByName(name))```

Any advice would be greatly appreciated

**Comment by beinmedia-tech** [comment]
same here

**Comment by tr3v3r** [comment]
Please check version 4.0.0
