### ISSUE TITLE
getting an error while installing 3.0.0

### ISSUE THREAD

**Issue by xomuss** [tr3v3r/react-native-esc-pos-printer#124]
Hello :)

I get an error during installation 3.0.0.
I noticed that was a similar some time ago [issues/45](https://github.com/tr3v3r/react-native-esc-pos-printer/issues/45)
Logs

npm ERR! code 1
npm ERR! path /Users/.../Data/oldProj/.../node_modules/react-native-esc-pos-printer
npm ERR! command failed
npm ERR! command sh -c node ./scripts/movelib.js
npm ERR! node:internal/modules/cjs/loader:1051
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module '/Users/.../Data/oldProj/.../node_modules/react-native-esc-pos-printer/scripts/movelib.js'
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:901:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
npm ERR!     at node:internal/main/run_main_module:23:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }
npm ERR! 
npm ERR! Node.js v20.9.0

**Comment by tr3v3r** [comment]
@xomuss  hi !
Thanks. 
Fixed in v.3.0.1

Just update
