### ISSUE TITLE
Epson TM-T70II Support

### ISSUE THREAD

**Issue by ahmad-tech** [tr3v3r/react-native-esc-pos-printer#127]
Does this package offer compatibility with the Epson TM-T70II? Although this printer is listed among the supported devices,
Supported Devices: https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/and2270.pdf

 I'm encountering difficulty locating it within the PRINTER_SERIES when attempting to utilize this package.

**Comment by tr3v3r** [comment]
yes it should support.
PRINTER_SERIES is a bit outdated I guess but getPrinterSeriesByName will return default series. So it should no be a problem for now.

**Comment by ahmad-tech** [comment]
Thanks for your response. I am developing a React Native application and encountering challenges in establishing a successful connection with the Epson TM-70II printer over the network. The printer has been configured on the local network and validated through various applications.

Here's a simplified example of the code I've written. It aims to monitor the printer's status, but I consistently receive an "UNKNOWN" status in the connection output.

`import React, {useEffect} from 'react';
import {Text} from 'react-native';
import EscPosPrinter from 'react-native-esc-pos-printer';

const PrintComponent = () => {
  useEffect(() => {
    EscPosPrinter.init({
      target: 'TCP:192.168.99.20',
      seriesName: 'EPOS2_TM_T70II',
      language: 'EPOS2_LANG_EN',
    })
      .then(() => {
        EscPosPrinter.addPrinterStatusListener(status => {
          console.log(status.connection, status.online, status.paper); // will be executed every 5 sec
        });

        EscPosPrinter.startMonitorPrinter(5)
          .then(() => console.log('Start monitor success!'))
          .catch((e: any) => console.log('Start monitor error:', e.message));
      })
      .catch(e => console.log('Init error:', e.message));
  }, []);

  return <Text>Print Logs</Text>;
};

export default PrintComponent;
`
