### ISSUE TITLE
Unable to print when wifi is turned off and then on(Only Android)

### ISSUE THREAD

**Issue by manage-some** [tr3v3r/react-native-esc-pos-printer#128]
The printer does not show any error and shows as connected when wifi is turned off and on. However the printer does not print on once wifi is reconnected. We have to restart the app to make it work.

Similarly if the app is in background for more than 5 minutes and then it is foregrounded the prints stops responding to print commands and the app needs to be restarted

**Comment by funkaarts** [comment]
+1

**Comment by tr3v3r** [comment]
Fixed in 4.0.0. See example folder
