### ISSUE TITLE
Not working on android

### ISSUE THREAD

**Issue by deounix** [tr3v3r/react-native-esc-pos-printer#14]
When I'm trying to call : `EscPosPrinter.init` app crashing with this error : `react native attempt to invoke virtual method 'double java.lang.double.doublevalue()'`

Also There's a typo >> `EscPosPrinter.discovery()` should be `EscPosPrinter.discover()` also this function returning an empty list (not showing printers connected via bluetooth)

**Comment by tr3v3r** [comment]
@deounix Hello!
Could you provide a bit more info?
At least the package version you're are using. Thanks

**Comment by MeSMedia** [comment]
I have the same problem

**Comment by samuel20miglia** [comment]
the same problem here

**Comment by tr3v3r** [comment]
@samuel20miglia @MeSMedia  could you please provide the info I've mentioned above?

**Comment by samuel20miglia** [comment]
Hi @tr3v3r ,

please find below the details about the issue:
react-native-cli: 2.0.1
react-native: 0.64.2

![photo_2021-08-02_16-04-03](https://user-images.githubusercontent.com/9152043/127874770-847eb7f4-6c96-4b21-93a6-55e36e6f5576.jpg)

Best Regards

**Comment by tr3v3r** [comment]
@samuel20miglia Thanks. 
Also, it would be nice if you could provide ]react-native-esc-pos-printer] version you are using and code snippet of how you call `init` method

**Comment by samuel20miglia** [comment]
react-native-esc-pos-printer: latest

![Screenshot 2021-08-02 at 16 36 17](https://user-images.githubusercontent.com/9152043/127878566-6b019853-22ce-40f5-a916-8b486441e91c.png)

**Comment by tr3v3r** [comment]
@samuel20miglia I suppose the problem is that you are using a printer produced NOT by Epson. 
Here is the list of all supported series names
```
EPOS2_TM_M10,
  EPOS2_TM_M30,
  EPOS2_TM_P20,
  EPOS2_TM_P60,
  EPOS2_TM_P60II,
  EPOS2_TM_P80,
  EPOS2_TM_T20,
  EPOS2_TM_T60,
  EPOS2_TM_T70,
  EPOS2_TM_T81,
  EPOS2_TM_T82,
  EPOS2_TM_T83,
  EPOS2_TM_T88,
  EPOS2_TM_T90,
  EPOS2_TM_T90KP,
  EPOS2_TM_U220,
  EPOS2_TM_U330,
  EPOS2_TM_L90,
  EPOS2_TM_H6000,
  EPOS2_TM_T83III,
  EPOS2_TM_T100,
  EPOS2_TM_M30II,
  EPOS2_TS_100,
  EPOS2_TM_M50,
  ```
  
  But anyway thanks for finding this bug. I'll add an assertion for this case

**Comment by samuel20miglia** [comment]
yes, sure
