### ISSUE TITLE
Skip location checking option for 2.x

### ISSUE THREAD

**Issue by JesperBadstue** [tr3v3r/react-native-esc-pos-printer#142]
Hi

I am using version 2.6.0 of this package and have to install it on Android devices without Google Play Services.
This means that printer discovery wont work.
The problem seem to be solved i v3.0.2 but our app is currently on an older version of React Native which means that I cant update the package.

Would it be possible to cherry-pick the fix from https://github.com/tr3v3r/react-native-esc-pos-printer/commit/b753586e07c1b152342a9b81f4434b63c1382031 and build a 2.6.1 version?

I have done a quick test locally with the changes from the commit and it seems to work fine with v 2.6.0

Regards
Jesper

**Comment by tr3v3r** [comment]
@JesperBadstue  I suppose there is no restriction regarding React Naive versions.

I'd propose instead of doing new releases to do a patch with the https://www.npmjs.com/package/patch-package

**Comment by JesperBadstue** [comment]
@tr3v3r you a probably right that a release for it is unnecessary. I will look into using patch-package until I can upgrade to >= v3.0.2
Thanks for the help and a great project.

**Comment by tr3v3r** [comment]
> @tr3v3r you a probably right that a release for it is unnecessary. I will look into using patch-package until I can upgrade to >= v3.0.2 Thanks for the help and a great project.

If any help needed feel free to reopen this issue
