### ISSUE TITLE
Use of undeclared identifiers

### ISSUE THREAD

**Issue by ahmad71666** [tr3v3r/react-native-esc-pos-printer#143]
<img width="1319" alt="Screenshot 2024-04-02 at 1 58 08 PM" src="https://github.com/tr3v3r/react-native-esc-pos-printer/assets/48828515/27a4281a-f4d7-427c-a282-c908aeb91128">

**Comment by tr3v3r** [comment]
@ahmad71666  hi I suppose this is an issue related to the latest xCode version.

Please try this beta version instead. The issue should gone

https://github.com/tr3v3r/react-native-esc-pos-printer/pull/139
