### ISSUE TITLE
ERR_TIMEOUT with Epson Printer U220

### ISSUE THREAD

**Issue by vsnaichuk** [tr3v3r/react-native-esc-pos-printer#144]
Hi, we have Epson U220 Printer and we are currently using beta version of this package. We've encountered an issue with this model of printer. When attempting to print, we receive the error `ERR_TIMEOUT`, `Failed to communicate with the device within the specified time`.

Platform
- [x] Android
- [x] iOS

We would greatly appreciate any assistance or guidance in resolving this issue

**Comment by tolypash** [comment]
+1

**Comment by tolypash** [comment]
@tr3v3r All prints to U220 fail and gibberish is being printed. Please take a look:

![IMG_1915](https://github.com/tr3v3r/react-native-esc-pos-printer/assets/22174779/55e40450-419c-465d-b844-72ed01fa3dfc)

Could you help us debug maybe? :)

**Comment by tolypash** [comment]
Okay, we have found the issue. We were passing EPOS_TM_U220 as the printer name (we had an override series setting).
Removing the override fixed it

**Comment by tr3v3r** [comment]
@tolypash hello! could you please explain a bit more in detail how it was at what you did to fix that?

Have you used the old version or a new one?

**Comment by tolypash** [comment]
Hello! So basically I was passing the wrong printer name (Instead of TM-U220 - I was passing EPOS2_TM_U220 (as a way of overriding the series from past version). Removing the override fixed it :)
