### ISSUE TITLE
Unhandled promise rejection [TypeError: privateMap.get is not a function. (In 'privateMap.get(receiver)', 'privateMap.get' is undefined)]

### ISSUE THREAD

**Issue by powershek** [tr3v3r/react-native-esc-pos-printer#145]
I am trying the 4.0.0-beta.5 version,  I can search the printer,  once I create a new Printer as below,  I got this error.   Please help

    new Printer({
      target: printer.target,
      deviceName: printer.model,
    })

Error:  Unhandled promise rejection [TypeError: privateMap.get is not a function. (In 'privateMap.get(receiver)', 'privateMap.get' is undefined)]

Environment : react-native: 0.66.0
                         react: 16.13.1
                         react-native-esc-pos-printer: 4.0.0-beta.5

**Comment by tr3v3r** [comment]
Hello @powershek,

Please provide a bit more information. Reproducible demo or at least code snippet. 

What typescript version do you use?

**Comment by powershek** [comment]
I search the printer,    result as below ,

    {"bdAddress": "", 
    "deviceName": "TM-T88VI", 
    "deviceType": "TYPE_PRINTER", 
    "ipAddress": "192.168.68.61", 
    "macAddress": "F8:25:51:7C:10:3B", 
    "target": "TCP:F8:25:51:7C:10:3B"
    }

and I store the information to AsyncStorage and retrieve to use  in the new Printer function 

new Printer({
  target: printer.target,
  deviceName: printer.deviceName,
})


I still using js to make my project.   any information need please let me know .  Thank you very much

**Comment by tr3v3r** [comment]
@powershek please show me the screenshot with error, I wanna see stacktrace. Also please show me how you do import from the lib

**Comment by powershek** [comment]
![beta5cap001](https://github.com/tr3v3r/react-native-esc-pos-printer/assets/76258891/34d41f09-8729-41b2-8a02-f799fd7665d8)

![beta5cap002](https://github.com/tr3v3r/react-native-esc-pos-printer/assets/76258891/305608d7-a4d5-4886-8eca-59b1cdba7cfb)

**Comment by powershek** [comment]
async function SimplePrint() {
        let printerlist = await API.getAllPrinter();

        console.log("printerlist====================", printerlist)
        let advmodemainprinter = await API.getAdvModeMainPrinter();
        console.log("advmodemainprinter====================", advmodemainprinter)
        let targerPrinterObj = printerlist.filter((filteritem) => filteritem.TID == advmodemainprinter)[0]
        let targerPrinter = printerlist.filter((filteritem) => filteritem.TID == advmodemainprinter)[0].selectedprinter
        console.log("targerPrinter====================", targerPrinter)
        setPrinter(targerPrinterObj)
        console.log("targerPrinterObj====================", targerPrinterObj)
        

        console.log("targerPrinterObj dtl====================", targerPrinterObj.item.target, targerPrinterObj.item.modal)

          let printerInstance2 = new Printer({
            target: `{targerPrinterObj.item.target}`,
            deviceName: targerPrinterObj.item.modal,
          })
 

    }

**Comment by tr3v3r** [comment]
For some reason, my message was not posted, but I've installed bare react native project (JS)  version 0.66.0 and tried to reproduce your issue. Unfortunately not luck... Everything works as expected.

For now, I'll close the issue bit If you could provide a reproducible demo please feel free to reopen it

**Comment by powershek** [comment]
I found the issue happen in Printer.ts, 

![image](https://github.com/tr3v3r/react-native-esc-pos-printer/assets/76258891/6b71bda1-afb3-42fb-992b-76630a6937fa)

![image](https://github.com/tr3v3r/react-native-esc-pos-printer/assets/76258891/9fa5296d-6e81-4564-bf45-a6e0b41b21fb)

![image](https://github.com/tr3v3r/react-native-esc-pos-printer/assets/76258891/5178ff64-9e2b-4b01-b7bd-0fa7722250c6)

Problem on this line,  

this.queue = new PQueue({ concurrency: 1 });


Could you please help

**Comment by JesusM15** [comment]
I have the same error

**Comment by tr3v3r** [comment]
@JesusM15  If possible provide reproducible repo

**Comment by JesusM15** [comment]
Unfortunately it's private, I can't, but we use node 18.18.0 with React Native 0.74.5 and my project also uses JS, not Typescript.
I only get this error when my code is inside my component like this:

const ClientsOrdersScreen = ({ navigation }) => {
  const dispatch = useDispatch();
  // elemntos para rotacion
  const [isTablet, setIsTablet] = useState(false);
  const [measuring, setMeasuring] = useState(true);
  const focus = useIsFocused();

  const printerInstance = useMemo(
    () =>
      new Printer({
        target: '192.168.1.25',
      }),
    []
  );

when I wrote code outside (only for records where the error does not appear), I get the error "INVALID PARAMETERS" when I call print.connect()

Sorry for my english.

**Comment by joanEstrada** [comment]
I solved it by adding the following lines to **package.json**:

`  "resolutions": {
    "p-queue": "6.6.2"
  }`

I found that the issue lies in the p-queue setup
