### ISSUE TITLE
hey all, I came across this repo while trying a few things on my Epson printers but i'm having trouble connecting to either of my printers (1 Lan and 1 USB) using this latest version `4.0.0-beta.6`

### ISSUE THREAD

**Issue by tr3v3r** [tr3v3r/react-native-esc-pos-printer#146]
hey all, I came across this repo while trying a few things on my Epson printers but i'm having trouble connecting to either of my printers (1 Lan and 1 USB) using this latest version `4.0.0-beta.6`

I'm just trying the example provided but i keep getting an Error `Printer is not initialized. Please call init() first.`

I've tried running printerInstance.init() before the queueTaks but no luck either. Any ideas why i might be getting this?

Thanks!

```

export const printSimpleReceipt = async (target, deviceName) => {
    try {
      const printerInstance = new Printer({
        target: target,
        deviceName: deviceName,
      })

      await printerInstance.addQueueTask(async () => {
        await Printer.tryToConnectUntil(
          printerInstance,
          (status) => status.online.statusCode === PrinterConstants.TRUE
        );

        await printerInstance.addText('Hello world!');
        await printerInstance.addFeedLine();
        await printerInstance.addCut();
        await printerInstance.sendData();

        await printerInstance.disconnect();
      })
   
    } catch (e) {
      throw e
  }
}
```

_Originally posted by @omarst9 in https://github.com/tr3v3r/react-native-esc-pos-printer/issues/139#issuecomment-2100644061_

**Comment by omarst9** [comment]
@tr3v3r the USB printer is TM-T88v and the LAN is TM-T82II

**Comment by tr3v3r** [comment]
@omarst9 before printing have you used printer discover? 

If it possible post the target and device name you're passing to Printer class

**Comment by omarst9** [comment]
Yes, I was using printer discover. I confirmed the taeget and deviceName were both correct 
```
   const printerInstance = new Printer({
      target: "USB:/dev/bus/usb/002/002",
      deviceName: "TM-T88V",
    });
```

I got it to work now after I rebuilt the app. I had the 3.0.2 version installed before i updated to 4.0.6 so that was most likely the reason.
