### ISSUE TITLE
Print Timeout on version 4.0.6-beta

### ISSUE THREAD

**Issue by omarst9** [tr3v3r/react-native-esc-pos-printer#150]
I noticed that when using an older USB printer (TM-T88IV) the print times out, while it prints normally on my newer USB printer TM-T88V. Even printing “Hello World” takes around 5 seconds on the older model. Has anyone experienced that?

**Comment by tr3v3r** [comment]
Have you experienced same on 3.1.1 version? Also please specify platform you're using

**Comment by omarst9** [comment]
I checked using 3.1.1 same issue. The printer model is not in the compatible devices list.
