### ISSUE TITLE
Bluetooth printer not discoverable

### ISSUE THREAD

**Issue by omarst9** [tr3v3r/react-native-esc-pos-printer#151]
I can't get bluetooth connectivity to work with 3.1.1 or 4.0.6 versions. The printer is not discoverable on android and on iOS.

Printer model is TM-m30III. I confirmed connection works over LAN/WIFI. 
I'm using Expo SDK 50.

I have added all the permissions needed for android and followed the steps in the installation guide.

Has anyone had any luck with getting Bluetooth printers working with this library?

If I add the Bluetooth MAC Address manually to the code with the device name i can connect and print from the printer. Its just the discovery isnt working.

**Comment by omarst9** [comment]
Hi @tolypash, i noticed you had a similar issue with Blutooth printers [here](https://github.com/tr3v3r/react-native-esc-pos-printer/pull/139#issuecomment-2062096968). Can I ask how you got discovery to work sometimes? And did you end up resolving the issue?

**Comment by tr3v3r** [comment]
Hello @omarst9,

I have this model and all works good at least with bare project. Have you paired your phone and printer before discovering?

With reproducible demon I can debug on my end

**Comment by omarst9** [comment]
Hi @tr3v3r,

Yes, I've paired the printer with the device first. I tried the example [here](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/arch-printer-reworked/example/src/screens/Discovery.tsx) and no bluetooth devices were discovered. (See attached image)

I tried the `react-native-thermal-receipt-printer` library and the printer was discovered so i'm not sure what could be wrong.

![no-bte-device](https://github.com/tr3v3r/react-native-esc-pos-printer/assets/40017704/a856b505-038b-4f17-9f7d-251d6dbc4ed8)

**Comment by tr3v3r** [comment]
@omarst9 have you tried increasing timeout? It helped me for Android
`discovery.start(10000)`

**Comment by omarst9** [comment]
That worked! I just tried it for Android and it detected the BT device. But still no luck with the iPad though

**Comment by tr3v3r** [comment]
> That worked! I just tried it for Android and it detected the BT device. But still no luck with the iPad though

Have you done all these steps?

<img width="845" alt="image" src="https://github.com/tr3v3r/react-native-esc-pos-printer/assets/23724142/ffc53f29-6cf0-486f-ae8e-6a367460226a">

**Comment by omarst9** [comment]
Yes, I already added those before building the iOS app and checked again to make sure they were there but still no BT device comes back from the discovery.

**Comment by tr3v3r** [comment]
@omarst9 and have you paired printer right with the device?

**Comment by tolypash** [comment]
@omarst9 you have to use pair Bluetooth function from the package.

**Comment by omarst9** [comment]
Yes, i’ve paired the device from the iOS bluetooth settings. 

I saw that pair bluetooth function but wasn’t too sure when to use it. Could you show me a snippet of when its used? Because from memory it needed the deviceName which means the BT printer needs to be discovered first.

**Comment by tolypash** [comment]
@omarst9 Disconnect the printer from iOS Bluetooth settings. Then request all necessary permissions from your app (Bluetooth, location). 

Then, call `PrintersDiscovery.pairBluetoothDevice()`

A native popup should appear and select your printer from there, it will connect, and now it will be paired properly.

**Comment by aargon007** [comment]
i have the same problem. stuck in two days but still not solve the problem

**Comment by aargon007** [comment]
> @omarst9 Disconnect the printer from iOS Bluetooth settings. Then request all necessary permissions from your app (Bluetooth, location).
> 
> Then, call `PrintersDiscovery.pairBluetoothDevice()`
> 
> A native popup should appear and select your printer from there, it will connect, and now it will be paired properly.

hey , i have connect the printer from popup. but later i can't find the printer. how can i get it?

**Comment by omarst9** [comment]
@aargon007 it never worked for me. I couldn't find the Bluetooth printer even after pairing

**Comment by tr3v3r** [comment]
> > @omarst9 Disconnect the printer from iOS Bluetooth settings. Then request all necessary permissions from your app (Bluetooth, location).
> > Then, call `PrintersDiscovery.pairBluetoothDevice()`
> > A native popup should appear and select your printer from there, it will connect, and now it will be paired properly.
> 
> hey , i have connect the printer from popup. but later i can't find the printer. how can i get it?
