### ISSUE TITLE
I cannot connect or pairing with bluetooth device on ios

### ISSUE THREAD

**Issue by wogno** [tr3v3r/react-native-esc-pos-printer#153]
I cannot see any bluethooth device with pairing and when I used start printers still  empty array. 

Too see if it's cause of my thermal, I downloaded app on appstore named thermer, and with this app, it discoevery and paired with my printer and also it allow me to print, 

So I don't know where is the problem, my app, printer or my code

"react-native-esc-pos-printer": "^3.1.1",
"react-native": "0.74.2",

![Capture d’écran 2024-06-23 à 17 16 42](https://github.com/tr3v3r/react-native-esc-pos-printer/assets/31076843/ebf2665b-d654-4f61-ad6b-7de1ae58022c)
![Uploading Capture d’écran 2024-06-23 à 17.20.09.png…]()

![image](https://github.com/tr3v3r/react-native-esc-pos-printer/assets/31076843/820917e0-1118-4a6e-800b-25bcadb267af)

**Comment by wogno** [comment]
![image](https://github.com/tr3v3r/react-native-esc-pos-printer/assets/31076843/6dd7e488-419f-4866-85e3-b98538f6227a)


My printer model

**Comment by tr3v3r** [comment]
Sorry @wogno  but the lib supports only printers produced by EPSON
