### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by markom983** [tr3v3r/react-native-esc-pos-printer#157]
Hey guys, does this package support EPSON TM-P80 C31CD70652 or epson tm-p60II ? I saw in the documentation that it supports, but I'm interested in your experiences with these two printers, I'm creating an application on which I will print some text and a qr code below it.

https://www.epson.co.za/en_ZA/products/retail/pos-printers/mobile-printers/epson-tm-p80-%28652%29%3A-receipt%2C-nfc%2C-bt%2C-ps%2C-eu/p/18371

**Comment by tr3v3r** [comment]
https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/and2270.pdf
