### ISSUE TITLE
Printers are not found (Bluetooth printer not discoverable in android)

### ISSUE THREAD

**Issue by hareshtech** [tr3v3r/react-native-esc-pos-printer#158]
@tr3v3r  does this package support HOP-H58 ? i am not able to found printers or any status

**Comment by ParasSoni2502** [comment]
SAME ISSUE

**Comment by tr3v3r** [comment]
Sorry guys the lib supports only printers produced by EPSON

**Comment by hareshtech** [comment]
@tr3v3r do we have any lib that support all type of Thermal receipt printers ?

**Comment by tr3v3r** [comment]
https://github.com/AllInOneYT/react-native-thermal-printer try this one
