### ISSUE TITLE
Custom Stylesheet

### ISSUE THREAD

**Issue by aargon007** [tr3v3r/react-native-esc-pos-printer#159]
I have been using this SDK. it's great and helpful. I want to customize the printing receipt design. how can i do that....
1. i want to add a border top and bottom with black 1px or 2 px height
2. i want to add tab space in addTextLine. can i do that?
3. can i create grid column?

**Comment by tr3v3r** [comment]
@aargon007 

1) for the line I see the corresponding method in the native SDK. It has to be exported to RN:

<img width="814" alt="image" src="https://github.com/user-attachments/assets/baa75d9d-3cca-472f-b0ba-dba7bd5c318b">
Here is an example how to do that: https://github.com/tr3v3r/react-native-esc-pos-printer/pull/164/files
2) What do you mean by tab space? Could you show me an example
3) ESC POS methods generally don't have a grid or flex system, so you most likely have to build something on your own.


I'd appreciate any ideas or contribution.

**Comment by aargon007** [comment]
Hi @tr3v3r , addLineSpace() working fine. but i want to add some space before a text line.

`await Printer.addTextLine(printerInstance, {
     left: `\t Item comped`,
     right: `-${priceInEuro(originalItemPrice(item))}`,
});`

I use \t for adding tab space but it didn't work. Also can you  please add the addHLine fuction in the package. 

![image](https://github.com/user-attachments/assets/10cfbc20-7fa8-4e59-acc2-13b0bda4e93a)

**Comment by aargon007** [comment]
wow amazing. i have using EscPosEncoder with your package. It's working awesome

**Comment by aargon007** [comment]
Hi @tr3v3r , is there any option setting font family for printed text?
