### ISSUE TITLE
Could Not invoke EscPosPrinterDiscovery.enableLocationSetting

### ISSUE THREAD

**Issue by TrustyTechSG** [tr3v3r/react-native-esc-pos-printer#160]
Hi, Thank you for the 4.0 update, just tried the latest version 4.0.1, Im facing this error with usePrintersDiscovery call, may I ask did I missed any dependency? My App is in a Monorepo setup and use to work good with https://github.com/januslo/react-native-bluetooth-escpos-printer

![image](https://github.com/user-attachments/assets/6146d6aa-3108-43d2-992e-32163aee9e8e)

**Comment by ronanru** [comment]
I'm running into the same issue. What's the fix here?

**Comment by tr3v3r** [comment]
@ronanru  I guess you **com.google.android.gms:play-services-location** dependency in Android somewhere and it could conflict with the lib.
 
@TrustyTechSG how you resolved this?

**Comment by TrustyTechSG** [comment]
hi @tr3v3r , I never resolved it, I was try to walk around it by use my existing library to do the scanning and then use this new 4.0 SDK to do the printing, but again facing another "Invalid params" error with the printer.connect call.

Tried to search in my project only find dependencies classpath 'com.google.gms:google-services:4.4.1', have no idea what is the root cause of this.

**Comment by tr3v3r** [comment]
Could you please check on the bare app ( clear RN )? Or try run [example folder](https://github.com/tr3v3r/react-native-esc-pos-printer/tree/main/example) and check if issue exist.
If it  is reproducible I can try to help.


But I think it is connected with some of the dependencies you're using in your app.
Please check what js libs or native libraries use com.google.android.gms:play-services-location?

**Comment by TrustyTechSG** [comment]
@tr3v3r I managed to reproduced it, it is caused by expo-location, simply install expo-location then you will face this error by calling start function from usePrintersDiscovery.

**Comment by sweebee** [comment]
Its the same when https://github.com/michalchudziak/react-native-geolocation is installed

**Comment by tr3v3r** [comment]
ok I'll try to update 'com.google.android.gms:play-services-location'

**Comment by tr3v3r** [comment]
Just released 4.1.4 with the fix.
I'd appreciate if you could validate if everything is OK now

@sweebee @TrustyTechSG @ronanru

**Comment by sweebee** [comment]
@tr3v3r Nice, tested and working!
