### ISSUE TITLE
Any way to set line space?

### ISSUE THREAD

**Issue by TrustyTechSG** [tr3v3r/react-native-esc-pos-printer#161]
Hi, does the new 4.0 version support set line space?

**Comment by tr3v3r** [comment]
@TrustyTechSG what you mean by "set line space"?

**Comment by TrustyTechSG** [comment]
Hi @tr3v3r, Sorry for not make is clear, like this, set the space between each row, the Esc/Pos command should be 0x1b 0x33 x

<img width="224" alt="image" src="https://github.com/user-attachments/assets/0efa4ed6-4b42-46e2-a399-255fbc0f0883">

**Comment by tr3v3r** [comment]
@TrustyTechSG check addFeedLine method. Seems one that you need

**Comment by TrustyTechSG** [comment]
@tr3v3r  Thank you for the quick response, yes the feed line can achieve the gap effect I send above, but some time user actually wan to make the line gap smaller to save paper. we have this setting supported in our web receipt printing,  and with native we are currently using our fold version of https://github.com/januslo/react-native-bluetooth-escpos-printer, it has the line space support, but having some issue on the iOS side.

**Comment by tr3v3r** [comment]
I see. 

There is an unexported method addLineSpace

<img width="753" alt="image" src="https://github.com/user-attachments/assets/3d90906b-d351-4f0e-94d9-d2f86c48f8f1">

You can raise a PR or I'll try to add it tomorrow. 

In the meantime you can try to use addCommand with the HEX command you shared above:

```javascript
import EscPosEncoder from 'esc-pos-encoder'; 

let encoder = new EscPosEncoder();

let result = encoder
    .initialize()
     .raw([  0x1b, 0x33 ])
    .encode(); // or any other way to get the Uint8Array

await printerInstance.addCommand(result);
```
Hope this helps.

**Comment by tr3v3r** [comment]
Just released v.4.1.0 with the corresponding addLineSpace method exported.

I didn't test it, so please provide feedback on how it works. 


https://github.com/tr3v3r/react-native-esc-pos-printer/releases/tag/v4.1.0

**Comment by TrustyTechSG** [comment]
@tr3v3r Thank you for the quick update, will try on it and provide you a update tomorrow.

**Comment by TrustyTechSG** [comment]
Hi @tr3v3r, just tried installed the latest 4.1.0 version, but Im still facing the error "Could not invoke EasPosPrinterDiscovery.enablelocationSetting" error right after calling the "start" function from usePrintersDiscovery. Do you have any idea what is the cause of this?

**Comment by tr3v3r** [comment]
This issue is resolved. Please let's discuss the location issue here 
https://github.com/tr3v3r/react-native-esc-pos-printer/issues/160
