### ISSUE TITLE
How to trigger the printer to open the cash drawer ?

### ISSUE THREAD

**Issue by MinaZakaria** [tr3v3r/react-native-esc-pos-printer#17]

**Comment by tr3v3r** [comment]
@MinaZakaria Hi!
What do you mean by Cash Drawer?

**Comment by MinaZakaria** [comment]
The Cash Drawer is the place that contains the money.
So times we need to open the drawer when printing the receipt to add more money.
There is a cable that connects from the Epson printer to the drawer. and then it wait for a command from the printer to open the cash drawer
![81CfVLfnBnL _AC_SL1500_](https://user-images.githubusercontent.com/25223413/130412093-f19db01c-12a9-41a9-b279-a90da09cfaef.jpg)

**Comment by tr3v3r** [comment]
@MinaZakaria  Thanks for the explanation!
Actually, to provide this functionality we need to add the corresponding method `addPulse` to handleCommand method for iOS and Android. Unfortunately, at the time I don't have the capacity to add it. But if you have, I'd really appreciate it ) 

https://github.com/tr3v3r/react-native-esc-pos-printer/blob/ba2ed89970993471d4538f1be6146be7a89ff671/ios/EscPosPrinter.m#L481

https://github.com/tr3v3r/react-native-esc-pos-printer/blob/ba2ed89970993471d4538f1be6146be7a89ff671/android/src/main/java/com/reactnativeescposprinter/EscPosPrinterModule.java#L487

Than we can just use it like:
```javascript
 printing()
 .addText('text')
 .addImage('logo.png`)
 .addPulse( // args )
 .addCut()
 
```

Here the method specification:
![image](https://user-images.githubusercontent.com/23724142/130423720-9dc6ab60-7d1b-4819-ad75-4360de8e8125.png)

**Comment by ahaikal** [comment]
@MinaZakaria a quick way to do this

```
import Encoder from 'esc-pos-encoder';
       ....
        const encoder = new Encoder();
        const printing = new EscPosPrinter.printing();
        encoder.pulse(0, 100, 100);
        const status = await printing.data(encoder.encode()).send();
```

This works for me

**Comment by tr3v3r** [comment]
Version 1.5.0 adds this functionality
