### ISSUE TITLE
Bluetooth printer not discovered in iOS

### ISSUE THREAD

**Issue by aargon007** [tr3v3r/react-native-esc-pos-printer#173]
### Description

I have been using Expo SDK 51 with react native .74. In my android build application the LAN,Wi-Fi and Bluetooth printer disscovered and working perfectly. But in iOS only LAN and Wi-Fi devices discovered. No bluetooth device found. I have implenent all hooks and methods but it not work. I have used PrintersDiscovery.pairBluetoothDevice() , pairBluetoothDevice from usePrintersDiscovery(). still not worked, it connected through the pop-up but not discovered. is there any way ? or this feature is not available?

I have added this infoPlist.

"infoPlist": {
                "UIRequiresFullScreen": true,
                "NSDocumentsUsageDescription": "This app requires access to the file system to store and retrieve data.",
                "NSFileProtectionComplete": "This setting ensures that files are protected.",
                "NSBluetoothAlwaysUsageDescription": "This app requires access to Bluetooth to connect to external devices.",
                "NSBluetoothPeripheralUsageDescription": "This app uses Bluetooth to connect to external devices.",
                "UISupportedExternalAccessoryProtocols": ["com.epson.ecpos"],
                "NSLocationAlwaysUsageDescription": "This app requires access to your location to find nearby Bluetooth devices.",
                "NSLocationWhenInUseUsageDescription": "This app requires access to your location to find nearby Bluetooth devices.",
                "NSUserTrackingUsageDescription": "This identifier will be used to deliver personalized ads to you.",
                "UIBackgroundModes": ["fetch", "remote-notification"],
                "NSAppTransportSecurity": {
                    "NSAllowsArbitraryLoads": true
                }
            },

### Steps to reproduce

1. I have disscover the device but not found
2. Paired the device through pairBluetoothDevice
3. Still not discovered

### react-native-esc-pos-printer version

4.1.3

### React Native version

0.74.5

### Platforms

iOS

### Workflow

Expo Dev Client

### Architecture

Paper (Old Architecture)

### Build type

Release app & production bundle

### Device

Real device

### Device model

iPad Air 2

### Acknowledgements

Yes

**Comment by tr3v3r** [comment]
@aargon007 thanks!
Can I ask you to please run the "example" folder and validate it?


Don't forget to pair the printer first.
Asking since I remember I tested the BE connection on iOS - and all was good.

**Comment by aargon007** [comment]
Thanks bro, i had typo in writting infoPlist. its working perfectly. you can close the issue now

**Comment by tr3v3r** [comment]
Can I ask you please to mention what was wrong here? Just to help others

https://github.com/tr3v3r/react-native-esc-pos-printer/issues/151
