### ISSUE TITLE
 Cannot read property 'getConstants' of null, js engine: hermes

### ISSUE THREAD

**Issue by anacarlapaiva** [tr3v3r/react-native-esc-pos-printer#177]
### Description

Hi, everyone!! 
My POS app in React Native is not able to support the library, always returning the error "Cannot read property 'getConstants' of null, js engine: hermes." Could you help me resolve this?

![image](https://github.com/user-attachments/assets/8281ce41-9a25-433e-bd79-da72b6e00fd7)

### Steps to reproduce

I just start the application with expo start 

### react-native-esc-pos-printer version

4.2.0

### React Native version

0.74.5

### Platforms

Android

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

EPSON TM-T20

### Acknowledgements

Yes

**Comment by jpkontreras** [comment]
Can you post the solution please?

**Comment by karaushu** [comment]
Same error with Expo 51 and React Native 0.74.5, why this issue is closed?
