### ISSUE TITLE
Can this library work in Expo? (EAS build with development client)

### ISSUE THREAD

**Issue by TrustyTechSG** [tr3v3r/react-native-esc-pos-printer#18]
Hi there, can this library work with Expo's latest development client and EAS build?

**Comment by tr3v3r** [comment]
@TrustyTechSG hello! Unfortunately I haven’t added any code to make lib compatible with  expo SDK.

**Comment by tr3v3r** [comment]
https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/EXPO.md

**Comment by TrustyTechSG** [comment]
> https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/EXPO.md

Thank you for the update.
