### ISSUE TITLE
receive events about printer status

### ISSUE THREAD

**Issue by NqCompiler** [tr3v3r/react-native-esc-pos-printer#19]
Hey,

Is it possible to get printer status from connected devices?

For example if paper is empty or the connection is lost

Keep up the great work!

**Comment by tr3v3r** [comment]
@NqCompiler hi! Sure. Please take a look at ‘startMonitorPrinter’. I suppose it returns all data you’ve mentioned.

moreover after every print - promise with corresponding data will be returned as well

**Comment by NqCompiler** [comment]
I had so many tabs open and was looking at the examples from your fork from react-native-thermal-receipt-printer and somehow ended up creating the issue at the right place.

Thanks for the fast response and help :)

**Comment by Rehankhalil462** [comment]
@tr3v3r  @NqCompiler  when device is connected using instantiate method, printing is working fine but this startsMonitorPrinter() is showing 
`DISCONNECT OFFLINE UNKNOWN` for 
```javascript
 EscPosPrinter.addPrinterStatusListener((status) => {

      console.log(status.connection, status.online, status.paper); // will be executed every 5 sec
    });
```

 What is the issue?
