### ISSUE TITLE
Image directory problem for imageAsset()

### ISSUE THREAD

**Issue by kamal-hossain** [tr3v3r/react-native-esc-pos-printer#23]
I'm trying to print image from my android device. 

In [this](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/PRINTING.md#image) doc it is instructed to store image on this path `android/app/src/main/assets`. So I have used expo [MediaLibrary](https://docs.expo.dev/versions/latest/sdk/media-library/) for download and store the image on `android/app/src/main/assets` path.

My actual image path is `file:///storage/emulated/0/android/app/src/main/assets/1634020369600.png`

And I am calling the the print function like that.
```js
printing.initialize().imageAsset('634020369600.png', 200);
```
This is the error that I am getting:
```
{
"nativeStackAndroid":[],
"userInfo":null,
"message":"1634020369600.png",
"code":"EUNSPECIFIED",
"line":2760,"
column":45,
"sourceURL":"http://localhost:8081/index.bundle?platform=android&dev=true&minify=false"
}
```

## It will be very much helpful if anyone can solve what I am missing.

**Comment by kamal-hossain** [comment]
Yes I need to print an remote image, but I have found that this package doesn't support remote image print, thats why I am trying to download and print the image.

**Comment by kamal-hossain** [comment]
Sure thing, give me some times. I am on it.

**Comment by kamal-hossain** [comment]
sorry I accidentally, closed the issue.

**Comment by kamal-hossain** [comment]
@tr3v3r 
I was about to give you huge thanks, becuase I did also printed successfully.
But there is a big problem. I want to print this kind of invoice.

![invoice](https://user-images.githubusercontent.com/47250512/136988345-00b66bff-3d3c-45b4-bd0a-d1eafb4ae27d.jpg)

---

## But look at this, this is the size if have printed with.

```
 .imageBase64(image, 630)
```
![WhatsApp Image 2021-10-12 at 9 48 53 PM](https://user-images.githubusercontent.com/47250512/136988642-2ecfc0b1-6072-40c4-91c9-d414fa8aaccb.jpeg)

Can I print the original height and width?

**Comment by tr3v3r** [comment]
@kamal-hossain Thanks to you too for the help!
Just released a new version to npm.
https://www.npmjs.com/package/react-native-esc-pos-printer

**Comment by tr3v3r** [comment]
@kamal-hossain no final app size will fine) we’ve already using it’s in production for iOS and Android

**Comment by kamal-hossain** [comment]
@tr3v3r 
Have you done anything for Remote image?
