### ISSUE TITLE
esc-pos-encoder is not compatible with Apple m1 arm architecture

### ISSUE THREAD

**Issue by AbuMareBear** [tr3v3r/react-native-esc-pos-printer#33]
The example app uses `esc-pos-encoder`. It does not currently work with Apple's sillicon chips.

**Comment by tr3v3r** [comment]
@AbuMareBear actually you don’t need esc pos encoder. It’s used for showing how to send raw data . So you can remove it

**Comment by AbuMareBear** [comment]
That's what I figured.
