### ISSUE TITLE
discover method doesn't always return connected printer on Android.

### ISSUE THREAD

**Issue by fragilehm** [tr3v3r/react-native-esc-pos-printer#36]
I am running the app on Android 11, with Epson `TM-m30II Bluetooth` printer connected (paired) but in the react-native app, the `discover` method is inconsistent, it doesn't always find a printer. Like if I put a reload button which calls the `discover` method it is not always returning the paired printer. Is it a known issue? (couldn't find anything related in https://github.com/tr3v3r/react-native-esc-pos-printer/issues).

**Comment by tr3v3r** [comment]
@fragilehm hello! Does behavior the same for other OS versions? What do you mean by “not always”? Could you please describe a bit in details please?



BTW you don’t need to pair device before discover. Try to disconnect it from device itself and retry discover.

**Comment by fragilehm** [comment]
Thanks for the quick reply!

https://user-images.githubusercontent.com/20160573/141795540-61a6ff4e-99a3-49c6-8ef6-eea27eadcb98.mov

On iOS it always returns the printer.

**Comment by tr3v3r** [comment]
@fragilehm what about versions below 11? 

As an option we can increase discovery time timeout. For now I stop it manually after 5 sec. you can try to change it here, re-run Android build and test.
https://github.com/tr3v3r/react-native-esc-pos-printer/blob/0eea276572c56469be30724dabcb4db3802d74df/android/src/main/java/com/reactnativeescposprinter/EscPosPrinterDiscoveryModule.java#L193

**Comment by fragilehm** [comment]
@tr3v3r didn't try on android 10, but most of your customers are on 11. I tried putting a higher number there like 10 seconds the printer is always returned. I see iOS also has the timeout `5 * NSEC_PER_SEC`, but at least from what I was testing it always returns the printer. So maybe it makes sense to allow passing the params in the `discover` method to set the `scanningTimeout` for Android and iOS separately? I can make a PR if you think that this is reasonable.

**Comment by tr3v3r** [comment]
@fragilehm I’d really appreciate it if you could add this possibility to pass timeout param!

**Comment by fragilehm** [comment]
@tr3v3r can you please review https://github.com/tr3v3r/react-native-esc-pos-printer/pull/37

**Comment by fragilehm** [comment]
Closing the issue as https://github.com/tr3v3r/react-native-esc-pos-printer/pull/37 addressed it with increasing the timeout for Android.
