### ISSUE TITLE
Is there anything to crop the image vertically?

### ISSUE THREAD

**Issue by kamal-hossain** [tr3v3r/react-native-esc-pos-printer#38]
Hey there, like [here](https://github.com/tr3v3r/react-native-esc-pos-printer/issues/23#issuecomment-954570461) we can define a width for the image. Is there anything so that we can crop the image below? Like maximum height?

It can be useful sometime if we wanna crop the image from below to save some paper.

**Comment by tr3v3r** [comment]
@kamal-hossain Hi! I think if you set height manually the image will be resized but not cropped. But if you have a capacity you could play with resize functions on the native size  ([Android](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/5ee153cd1017ac9784b18a7324a978347a0d013f/android/src/main/java/com/reactnativeescposprinter/EscPosPrinterModule.java#L678, [iOS](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/5ee153cd1017ac9784b18a7324a978347a0d013f/ios/EscPosPrinter.m#L517))
