### ISSUE TITLE
Build failed on M1 mac

### ISSUE THREAD

**Issue by danielminhnguyen** [tr3v3r/react-native-esc-pos-printer#39]
Hi guys, when building on xcode for simulator I received this error

`in /Users/hokkinxx/Code/FullStack/PosAppv2/node_modules/react-native-esc-pos-printer/ios/PrinterSDK/libepos2.a(Epos2ConnectionInfo.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/hokkinxx/Code/FullStack/PosAppv2/node_modules/react-native-esc-pos-printer/ios/PrinterSDK/libepos2.a' for architecture arm64`

**Comment by tr3v3r** [comment]
@danielminhnguyen Unfortunately I don't have a machine on M1. So the only thing that I could propose is trying to update to the latest SDK (download from here https://download.epson-biz.com/modules/pos/index.php?page=soft&pcat=3&scat=58).
And try to replace libepos2.a with a new one.

 Possibly the issue has already been solved by the Epson guys.

**Comment by danielminhnguyen** [comment]
I tried to replace but still it doesn't work, if I change target build to physical device then it works. I think I can live with that for the time being. Thank you @tr3v3r for you awesome works!

**Comment by fragilehm** [comment]
@tr3v3r Hi, is there a way to know if both ios and android SDKs are up to date? or which version of the SDKs this package is using?

**Comment by tr3v3r** [comment]
Hi, @fragilehm 
Current version of SDK is 2.17.1 (iOS, Android)

For convenience I have a plan to extract SDK into separate npm lib with appropriate documentation and version history. Just trying to find time in my schedule)

**Comment by tr3v3r** [comment]
Just release v2.2.0.
SDK updated to v.2.22.0. Android 12 support added.

[Installation docs](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/INSTALLATION.md) updated 

Checked. Build with M1 works
