### ISSUE TITLE
What kind of printer should I buy?

### ISSUE THREAD

**Issue by vega99** [tr3v3r/react-native-esc-pos-printer#41]
Hello everyone, I would like to know what printer is the best to use with this library.... thanks in advance!!!

**Comment by tr3v3r** [comment]
@vega99 Hello!
This library uses SDK for the TM printers produced by **EPSON**.
So here is the list of supported printers:
![image](https://user-images.githubusercontent.com/23724142/145961250-89296929-7d03-4af0-9bce-1eb75d1fbd2a.png)

**Comment by vega99** [comment]
> @vega99 Hello!
> This library uses SDK for the TM printers produced by **EPSON**.
> So here is the list of supported printers:
> ![image](https://user-images.githubusercontent.com/23724142/145961250-89296929-7d03-4af0-9bce-1eb75d1fbd2a.png)
> 

Thank you so much
