### ISSUE TITLE
Font B (or finer font size control)

### ISSUE THREAD

**Issue by rissois** [tr3v3r/react-native-esc-pos-printer#43]
### PROBLEM
A quick annotation of font size and characters per line for the TM-T20II:
```
1: 48 // Fairly default size
2: 24 // Overly large and impractical, like going from a 12 to a 24 on a Word document
3: 16 // Maybe a header
4: 12 // Really only useful for strings of static length
5: 9? // What's the use?
6: 8 // Are these really necessary?
7: 6? // I mean, come on
8: 6 // maybe for a 6 digit code...
```

### DISCUSSION
If I understand the [Epson documentation](https://files.support.epson.com/pdf/pos/bulk/tm-i_epos-print_um_en_revk.pdf) correctly, and the API limitations thereby imposed on this package, there is little we can do to fix this (frankly insane) integer-based scaling. Correct me if I am wrong?

Therefore, we should try to introduce addTextFont to introduce smaller font sizes and afford **some** degree of finer font size. As far as I can tell, all models accept Font B so we can focus on that and ignore potential errors with Font C.

**Comment by tr3v3r** [comment]
@rissois hello! Why not ? We can add any methods exported by the native SDK. I’d really appreciate any contributions here!

**Comment by rissois** [comment]
@tr3v3r addTextSize only takes integer values (1, 2, 3... etc) and not more specific values like 1.3 or 2.75, for example. Therefore it looks like you can only print at 1X, 2X, 3X, 4X (etc) the default size, and cannot print at 1.3X or 2.75X.

I tried to fork and contribute, but got very lost along the way. Particularly with the native code. I hope to try again someday.
