### ISSUE TITLE
getting error while installing

### ISSUE THREAD

**Issue by devudr** [tr3v3r/react-native-esc-pos-printer#45]
error logs

/Users/../Documents/work/ReactNative/work/../node_modules/react-native-esc-pos-printer: Command failed.
Exit code: 1
Command: node ./scripts/movelib.js
Arguments: 
Directory: /Users/../Documents/work/ReactNative/work/../node_modules/react-native-esc-pos-printer
Output:
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/Users/../Documents/work/ReactNative/work/../node_modules/react-native-esc-pos-printer/scripts/movelib.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {

**Comment by tr3v3r** [comment]
Fixed in v1.7.1

**Comment by devudr** [comment]
hi @tr3v3r  what is the major difference in v1.5.0 between v1.7.1

**Comment by tr3v3r** [comment]
@devudr the only difference is that SDK for iOS is moved to a separate repo.
