### ISSUE TITLE
iPad Not working 

### ISSUE THREAD

**Issue by devudr** [tr3v3r/react-native-esc-pos-printer#46]
Hi @tr3v3r 
I am using **Epson TM-T88VI** printer with same network wifi
 
EscPosPrinter.discover()
  .then((printers) => {
    alert(printers[0]);
  })
  .catch((e) => console.log('Print error:', e.message));

alert not coming please assist me.

library v1.5.0

**Comment by tr3v3r** [comment]
@devudr after investigation, I realized that the current SDK version doesn't support your printer.
I need to update it.

**Comment by devudr** [comment]
hi @tr3v3r 
I need to add object of printing iteration please assist
.

**Comment by tr3v3r** [comment]
@tr3v3r Just updated to v.1.8.0   with Android SDK updates. Could please confirm that printer is now could be detected on Android?

**Comment by devudr** [comment]
Hi @tr3v3r  Currently I am working only for  iOS Platform using v1.5.0.
yes its working

**Comment by devudr** [comment]
Hi @tr3v3r 

printing.initialize().text("hello, is it me you're looking for").send();

how can i add text from loop its not working for me
