### ISSUE TITLE
Xcode 13 build failed 

### ISSUE THREAD

**Issue by devudr** [tr3v3r/react-native-esc-pos-printer#47]
Hi @tr3v3r 

I am facing the issue with Xcode 13 Version 

**node_modules/react-native-esc-pos-printer/ios/PrinterSDK/libepos2.a' for architecture arm64**

**Comment by ngondat97** [comment]
the same

**Comment by AzranAzwer** [comment]
any fixes ?

**Comment by AzranAzwer** [comment]
Hi All I fixed this issue by,
1. delete Pod file and pod.lock file
2. delete derived data folder (by preference -> location -> derived data folder)
3. XCode -> target file -> excluded architecture -> both debug and release  -> Any Ios simulator SDK -> add "arm64"
4. Quite XCode
5. right click on Xcode -> info -> check open by Rosetta
6. restart your macbook
7. clean and run it will work

**Comment by PedramGhdi** [comment]
Same problem, and not fixed by your suggestion @AzranAzwer.
Owner? @tr3v3r

**Comment by PedramGhdi** [comment]
I tried to run it on a real device and now there is no error.
I think it has a problem with the simulator.
