### ISSUE TITLE
"No permissions granted" error throw from discover()

### ISSUE THREAD

**Issue by TrustyTechSG** [tr3v3r/react-native-esc-pos-printer#49]
Hi @tr3v3r , Checked my App from system settings already have location permission, can I know which permission missing can lead to this error when calling discover().

**Comment by yakuphanbilgic** [comment]
Having the same problem with an Android device. I have already added required permissions to AndroidManifest.xml. Meanwhile on iOS emulator I am not getting any errors.

**Comment by tr3v3r** [comment]
@TrustyTechSG hi! Could you please share a bit more info about the environment?

RN version, Android version and etc. Everything that could help to reproduce an issue.
Thansk
