### ISSUE TITLE
Does this library provide printer via usb connection?

### ISSUE THREAD

**Issue by MuhammetAdamoglu** [tr3v3r/react-native-esc-pos-printer#5]
I connected esc pos with usb on android device. Different applications can communicate. There is no problem with the connection. However, your library gives an empty array when I use discover.

**Comment by tr3v3r** [comment]
@MuhammetAdamoglu that’s strange because resentful we tested this functionality. Here the corresponding pr https://github.com/tr3v3r/react-native-esc-pos-printer/pull/3


Could you please share a bit more information. 

Printer model, android os, type of connection (usb B, usb A )

**Comment by LuisMSotamba** [comment]
I have the same problem. I build a simple react native app for connect my cellphone to thermal printer. When I use discover method for find out devices I get an empty array as answer. 
Printer model is BT-IIX.

**Comment by tr3v3r** [comment]
@LuisMSotamba I'm afraid we only support printers produced by Epson for now ;(
