### ISSUE TITLE
Support the TM-T90?

### ISSUE THREAD

**Issue by kiyohken2000** [tr3v3r/react-native-esc-pos-printer#53]
Hello @tr3v3r ,

I have a TM-T90 on my local network. I can be discovered by `discover()`.

{
  "bt": "",
  "ip": "192.168.10.135",
  "mac": "50:57:9C:58:08:21",
  "name": "TM-T90",
  "target": "TCP:50:57:9C:58:08:21",
  "usb": ""
}

However, when I run print, it returns `ERR_UNSUPPORTED`.
I have two other printers, a TM-m30II-H and a TM-m10, and these two printers print fine.
Only the TM-T90 returns this error.

Thanks!

**Comment by tr3v3r** [comment]
@kiyohken2000 

[here](https://download.epson-biz.com/epson/epson_public_document.php?name=and2200.pdf) the list of supported printers


I'll try to update SDK to the latest one soon - you can check one more time if it helps

**Comment by tr3v3r** [comment]
@kiyohken2000 just release new version with the latest SDK. But I don't have possibility to verify that everything works ( don't have printer now )

Could you please install v1.11.0 and verify that it works for Android and iOS, please?

https://www.npmjs.com/package/react-native-esc-pos-printer
Will be really appreciate it
