### ISSUE TITLE
Error: [TypeError: _reactNativeEscPosPrinter.default.printRawData is not a function

### ISSUE THREAD

**Issue by justinbelardi** [tr3v3r/react-native-esc-pos-printer#55]
Hi! I have an application that sends the Encoded Bytes for escpos printers from the server and was hoping to use the `EscPosPrinter.printRawData()` functionality that I found in the API doc to send the bytes to network printers. When trying to use it, I get the following error:

`Error: [TypeError: _reactNativeEscPosPrinter.default.printRawData is not a function. (In '_reactNativeEscPosPrinter.default.printRawData(raw_bytes)', '_reactNativeEscPosPrinter.default.printRawData' is undefined)]`

I was able to get successful prints using the Quick Print Example. Any help you can provide is greatly appreciated!

**Comment by tr3v3r** [comment]
@justinbelardi  hello!

printRawData() doesn't exist, so use this method please:
https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/PRINTING.md#data
it do the same  ;)

It expects that **data as uint8ArrayData** will be passed as an argument


hope this helps.
