### ISSUE TITLE
It is possible to make this lib work with printers outside epson?

### ISSUE THREAD

**Issue by marianolc** [tr3v3r/react-native-esc-pos-printer#56]
I know that is a SDK thing.. but im curious if someone made it work with other printers. I've tried several options in the config but I keep getting ERR_CONNECT. The printer using pure ESC/POS works well sending the bytes directly to the IP.

**Comment by tr3v3r** [comment]
@marianolc  I suppose it's not possible ;(

Try to use https://www.npmjs.com/package/react-native-thermal-printer I suppose it should work with any type of printers since it's not based on any brand SDK
