### ISSUE TITLE
Epson printer text left and right

### ISSUE THREAD

**Issue by ManveeYew** [tr3v3r/react-native-esc-pos-printer#57]
Can any one provide example of how to print texts align left and right in the same line? Can't seem to find it anywhere. Help is appreciated!!

**Comment by tr3v3r** [comment]
@ManveeYew hello ESC/POS doesn't support such functionality out of the box. However, it's possible to do it manually, I plan to prepare a function in the near future. 

The main idea is to use this [method](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/API.md#getprintercharsperlineseriesname) and adjust the layout manually.

**Comment by ManveeYew** [comment]
Thanks @tr3v3r , without this it doesnt really meaningful to print POS receipt.  Can't wait for this function!

**Comment by PedramGhdi** [comment]
Hi, What should we do to have 2 texts in one line?

**Comment by tr3v3r** [comment]
@PedramGhdi hi I’m currently working on it. I’ll keep you posted on updates

**Comment by ManveeYew** [comment]
hi @PedramGhdi, currently i used a work around to get this to work. 

`/**
 * utility: pads two strings to columns per line
*/
const getSplitMessage = (
  value: string,
  value2: string,
  columnPerLine?: number,
) => {
  columnPerLine = 48;
  let finalString = '';
  if (value.length + value2.length > columnPerLine) {
    finalString = value + ' ' + value2;
  } else {
    let padding = columnPerLine - (value.length + value2.length);
    finalString = finalString + value;
    for (let i = 0; i < padding; i++) {
      finalString = finalString + ' ';
    }
    finalString = finalString + value2;
  }
  return finalString;
};`

`format.size(1, 1).text(getSplitMessage('Product', 'Total'))`

**Comment by PedramGhdi** [comment]
> @PedramGhdi hi I’m currently working on it. I’ll keep you posted on updates

It'll be great! thanks

**Comment by tr3v3r** [comment]
Just released 2.3.0 version.
Please try this method https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/PRINTING.md#textline
