### ISSUE TITLE
Trying to print on multiple BT printers simultaneously

### ISSUE THREAD

**Issue by ManveeYew** [tr3v3r/react-native-esc-pos-printer#60]
try using try catch await to print to multiple Bluetooth printers at once, always get error 'ERR_CONNECT'  and  'ERR_ILLEGAL' on second print.

my code
`
try {
  await EscPosPrinter.init({
    target: `BT:${print.ip.toString()}`,
    seriesName: getPrinterSeriesByName(print.name),
    language: 'EPOS2_LANG_EN',
  });
  let printing: Printing = await getEpsonOrderData(print.data);
  await printing.send();
} catch (e) {
  console.log(e);
}
`

**Comment by bp1295** [comment]
I am having the same issue trying to print on multiple printers. I'm guessing the two initializations in quick succession are causing the issue, but I haven't found anything definitive.

**Comment by tr3v3r** [comment]
@beinggandhi  that's actually one of the point from my TODO list. Trying to find time for it...

For now you can try to test the workaround suggested in [this](https://github.com/tr3v3r/react-native-esc-pos-printer/issues/12) thread

**Comment by tr3v3r** [comment]
Multiple prints are now supported

please check [docs](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/API.md#instantiate-target-seriesname-language)
