### ISSUE TITLE
Bluetooth discovery not working with IOS

### ISSUE THREAD

**Issue by TwenLeMammouth** [tr3v3r/react-native-esc-pos-printer#61]
Hi, 
Sorry I have another problem, nothing is discovered with bluetooth even after pairing the printers first it the Ipad settings, or by using 'pairingBluetoothPrinter()'.
Also, I tried using the printers in USB, but couldn't find anything either, and none of the printer's internal settings talk about USB, is it really possible to use it.?

**Comment by me-ibad** [comment]
I am also facing an issue with print by Bluetooth on IOS

**Comment by fragilehm** [comment]
@TwenLeMammouth which printer model are you using for Bluetooth?

**Comment by TwenLeMammouth** [comment]
It was TM-m30, but I don't have them anymore..

**Comment by fragilehm** [comment]
This doesn't work for me either when I run the example project. But it works when I install the package to my own project.

**Comment by jaaahh** [comment]
add this to info.plist file.

```
		<key>UISupportedExternalAccessoryProtocols</key>
		<array>
			<string>com.epson.escpos</string>
		</array>
```

**Comment by tr3v3r** [comment]
It would be great if someone could update the example project since I don't have Bluetooth printer to test. (only LAN)

@fragilehm  @jaaahh  ? =)

**Comment by tolypash** [comment]
@jaaahh solution worked for me!
So now bluetooth works great

**Comment by tr3v3r** [comment]
Close issues since the install section contains this info:

https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/INSTALLATION.md#when-the-bluetooth-or-usb-is-used-set-the-protocol-name-set-the-protocol-name-according-to-the-following-procedure
