### ISSUE TITLE
imageBase64 not work in iOS

### ISSUE THREAD

**Issue by chukiatt** [tr3v3r/react-native-esc-pos-printer#63]
Hi 

i got error when using base64Image
 
printing.initialize().imageBase64(base64Image, 75);

ERROR : "Calling [RCTConvert UIImage:] on a background thread is not recommended"

**Comment by tr3v3r** [comment]
@chukiatt It's a worning from RN source  code
https://github.com/facebook/react-native/blob/3addafa5257ade685216900bebbad8c35e24e124/React/Base/RCTConvert.m#L1226
