### ISSUE TITLE
TimeoutException com.epson.epos2.printer.Printer.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by vargal** [tr3v3r/react-native-esc-pos-printer#64]
I know that this error has already been discussed, but even when using the latest SDK for Android (V2.20) I still have this issue.

java.util.concurrent.TimeoutException: com.epson.epos2.printer.Printer.finalize() timed out after 10 seconds
    at com.epson.epos2.printer.Printer.nativeEpos2Disconnect(Printer.java)
    at com.epson.epos2.printer.Printer.finalize(Printer.java:7)
    at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:229)
    at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:207)
    at java.lang.Thread.run(Thread.java:818)

The problem is that we have a fleet of devices, and this error is hard to reproduce. The application crashes several times per day on certain devices. Given that the Android OS is handling this error, it kills the app and you cannot control it. 

Any suggestion on how to mitigate this error ?

**Comment by vargal** [comment]
Thanks @tr3v3r. In case others are looking at this issue, one patch to overcome the application to crash is to catch the TimeoutException from the FinalizerWatchdogDaemon.

```
final Thread.UncaughtExceptionHandler defaultUncaughtExceptionHandler =
                Thread.getDefaultUncaughtExceptionHandler();
        Thread.setDefaultUncaughtExceptionHandler((t, e) -> {
            if (t.getName().equals("FinalizerWatchdogDaemon") && e instanceof TimeoutException) {
                assert true; //ignore this
            } else {
                if (defaultUncaughtExceptionHandler != null) {
                    defaultUncaughtExceptionHandler.uncaughtException(t, e);
                }
            }
        });
```


Of course, this is only a workaround that apparently is working.

**Comment by LucNguyen98** [comment]
> Thanks @tr3v3r. In case others are looking at this issue, one patch to overcome the application to crash is to catch the TimeoutException from the FinalizerWatchdogDaemon.
> 
> ```
> final Thread.UncaughtExceptionHandler defaultUncaughtExceptionHandler =
>                 Thread.getDefaultUncaughtExceptionHandler();
>         Thread.setDefaultUncaughtExceptionHandler((t, e) -> {
>             if (t.getName().equals("FinalizerWatchdogDaemon") && e instanceof TimeoutException) {
>                 assert true; //ignore this
>             } else {
>                 if (defaultUncaughtExceptionHandler != null) {
>                     defaultUncaughtExceptionHandler.uncaughtException(t, e);
>                 }
>             }
>         });
> ```
> 
> Of course, this is only a workaround that apparently is working.

I'm not familiar with Android code. Where can I add this code?

**Comment by manny-cuboh** [comment]
@LucNguyen98 Did you ever find where to add the code? Having the same issue

**Comment by LucNguyen98** [comment]
> @LucNguyen98 Did you ever find where to add the code? Having the same issue cc @vargal

I still have not found

**Comment by tr3v3r** [comment]
Closed because of innactivity
