### ISSUE TITLE
[Help/Question] Printing to Multiple Printers Simultaneously 

### ISSUE THREAD

**Issue by beinggandhi** [tr3v3r/react-native-esc-pos-printer#65]
Hey Group, 

Thanks for this effort. 
We are looking to implement support for epson printers. 

Our usecase requires us to split the order and print the relevant parts of the order to multiple Printers Simultaneously. 
Looking at the current codebase, seems the current repo might not be able to handle this properly. Has anyone tried doing this.

**Comment by tr3v3r** [comment]
@beinggandhi duplicate. 

https://github.com/tr3v3r/react-native-esc-pos-printer/issues/60
