### ISSUE TITLE
discover method crash app on Android 12 when bluetooth is on.

### ISSUE THREAD

**Issue by karaushu** [tr3v3r/react-native-esc-pos-printer#69]
On Android 12 when try to `EscPosPrinter.discover()` app crash without any error.
But when `EscPosPrinter.init()` with already known info it works (LAN/USB).
Seems some bluetooth issue with Android 12, If bluetooth is on - app crash on `discover()`, otherwise everything work fine.

### Tested devices
Samsung S20 FE (android 12) - crash when bluetooth is on.
Samsung A51 (android 12) - crash when bluetooth is on.
LG G6 (android 9) - works fine.

discover params 
```js
{
  scanningTimeoutIOS: 10000,
  scanningTimeoutAndroid: 10000,
}
```
### Env
EXPO SDK 46 ejected
"react-native": "0.69.5",
"react-native-esc-pos-printer": "^2.0.0",
No Expo
"react": "18.1.0",
"react-native": "0.70.0",
"react-native-esc-pos-printer": "^2.0.0"

Printer: TM-m30
permissions: 
```json
"permissions": [
  "CAMERA",
  "NOTIFICATIONS",
  "BLUETOOTH",
  "BLUETOOTH_ADMIN",
  "ACCESS_COARSE_LOCATION",
  "ACCESS_FINE_LOCATION",
  "INTERNET"
],
```

**Comment by karaushu** [comment]
Find the solution: for Android 12 need to request for `BLUETOOTH_CONNECT` and `BLUETOOTH_SCAN` before discover.

**Comment by Rehankhalil462** [comment]
@karaushu   "CAMERA",
  "NOTIFICATIONS",
  "BLUETOOTH",
  "BLUETOOTH_ADMIN",
  "ACCESS_COARSE_LOCATION",
  "ACCESS_FINE_LOCATION",
  "INTERNET"

can I put these same permission in expo react native app.json android permissions array? or i need to modify like android.permissions.BLUETOOTH etc for all permissions?

I am using Expo Dev Client with expo 46 sdk.

**Comment by karaushu** [comment]
app.json it's enough. But you should ask for [those permissions](https://github.com/tr3v3r/react-native-esc-pos-printer/issues/85#issuecomment-1387045509) before discover.

**Comment by Rehankhalil462** [comment]
@karaushu  

 after executing the following code ,
try {
const printers = await EscPosPrinter.discover();
console.log("printers", printers);
} catch (error) {
console.log("Error:", error);
}

getting the following console errors

requestAndroidPermissions false
Error: No permissions granted

I am using Expo React Native in Dev Client. and added these "permissions": [
"android.permission.BLUETOOTH",
"android.permission.BLUETOOTH_ADMIN",
"android.permission.BLUETOOTH_CONNECT",
"android.permission.BLUETOOTH_SCAN",
"android.permission.INTERNET",
"android.permission.WRITE_EXTERNAL_STORAGE",
"android.permission.READ_EXTERNAL_STORAGE",
"android.permission.ACCESS_COARSE_LOCATION"
],

in app.json file.

Even if I request BLUETOOTH_CONNECT and BLUETOOTH_SCAN permissions using PermissionsAndroid from react native it is giving this response {"android.permission.BLUETOOTH_CONNECT": "never_ask_again", "android.permission.BLUETOOTH_SCAN": "never_ask_again"}.

can you please check what is the issue ?

**Comment by karaushu** [comment]
As i say you should ask for permissions before discover.

**Comment by Rehankhalil462** [comment]
try {
     const data = await PermissionsAndroid.requestMultiple([
          "android.permission.BLUETOOTH_CONNECT",
          "android.permission.BLUETOOTH_SCAN",
        ]);
console.log('data',data)
const printers = await EscPosPrinter.discover();
console.log("printers", printers);
} catch (error) {
console.log("Error:", error);
}

i did this but getting following 

 LOG  data {"android.permission.BLUETOOTH_CONNECT": "never_ask_again", "android.permission.BLUETOOTH_SCAN": "never_ask_again"}
 LOG  requestAndroidPermissions false
 LOG  Error: No permissions granted

**Comment by karaushu** [comment]
well, result is _'_never_ask_again'_. You should execut only when permissions is _'granted'_.
Eg:
```js
const status = await PermissionsAndroid.request(
  'android.permission.BLUETOOTH_CONNECT'
);
if (status === 'granted') {
 // do discover
 }
```
Try to reset in expo dev client permissions.

**Comment by Rehankhalil462** [comment]
@karaushu  i tried this. but the issue is , it is not even opening a prompt to allow or deny permissions.

**Comment by Rehankhalil462** [comment]
@karaushu  if i execute PermissionsAndroid.request('android.permission.ACCESS_FINE_LOCATION) 
it is opening prompt to allow or deny. but not for bluetooth scan and bluetooth connect permission.
 can you please share app.json android configuration for permissions for expo? so i can check maybe I would have an issue in app.json

**Comment by karaushu** [comment]
`
permissions: [
			'CAMERA',
			'NOTIFICATIONS',
			'BLUETOOTH',
			'BLUETOOTH_ADMIN',
			'BLUETOOTH_SCAN',
			'BLUETOOTH_ADVERTISE',
			'BLUETOOTH_CONNECT',
			'ACCESS_COARSE_LOCATION',
			'ACCESS_FINE_LOCATION',
			'INTERNET',
		],
`

**Comment by Rehankhalil462** [comment]
@karaushu  thanks. it is working now . But when i open the application there is a warning

```javascript
`new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.`

also receipt quality is not good when  printing a base64 png image . is there any configuration to do? i am using epson tm-p20.

**Comment by tr3v3r** [comment]
@Rehankhalil462  don't worry about this warning. It's a minor implementation bug that will be fixed.

Image issues let's discuss [here](https://github.com/tr3v3r/react-native-esc-pos-printer/issues/89)
