### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by reckyidx** [tr3v3r/react-native-esc-pos-printer#7]
When i try to run a package, i get following error
`import type{
PrinterEvents,
EventListenerCallback,

} at node_modules\react-native-esc-pos-printer\src\index.tsx 13:12   :unexpected token`

**Comment by tr3v3r** [comment]
@reckyidx Hi!

Could you please provide a bit more info?

Platform (iOS, Android)
React Native version
TypeScript version

Also, it would be nice if you show a piece of code where you are experiencing the issue.

Thanks
