### ISSUE TITLE
Can't discover on my RN App

### ISSUE THREAD

**Issue by PHidalgo1** [tr3v3r/react-native-esc-pos-printer#70]
I'm trying to discover an Epson TM-T20II via USB, after following the install instructions (i've installed both react-native-esc-pos-printer and the SDK) and adding the quick test print function, it comes with nothing.
Already tried many options on how to work it, maybe missing some USB permissions on the AndroidManifest, etc, but neither seems to work at all, program gets to 

`const printers = await EscPosPrinter.discover();`

And that's it, am i missing something?

Edit: on a side note i'm getting these warning as well
`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
`new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.

**Comment by tr3v3r** [comment]
@PHidalgo1 hi!
Did able to connect your printer to your PC (via USB) and print something? 

Asking because to make the printer work with a particular type of connection, sometimes you need to update the settings of the printer itself.

**Comment by PHidalgo1** [comment]
@tr3v3r heya! 
The funny thing is that i was able to discover and print a receipt through an example app EPSON had with the ePOS.jar, and also another module i had to work on for a Sewoo printer, but it's done through bridging a bunch of Java code instead of doing through your module, that said, i can connect the printer to my pc and try and see which settings are there just in case

**Comment by manage-some** [comment]
Same happend with me. I have three devices. On one IOS and Android it worked fine. But on another Android, it's stuck on discover, doesn't even throw error

**Comment by manage-some** [comment]
+1 I'm also stuck on discover on my sumni v2 device with android 11. The discover option worked perfectly on another android 13 device

**Comment by Waleed065** [comment]
+1 I'm also stuck on discover on my sumni v2 device with android 11. The discover option worked perfectly on another android 13 device

**Comment by tr3v3r** [comment]
The lib supports only devices produced by EPSON.

Please also check if your device is supported here:

[Android](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/and2270.pdf)
[iOS](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/and2270.pdf)

Also, you can try to play with [filter options](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/interfaces/discoveryStartParams.md) introduced in v.3.0.0

For now, closing the issues. Please feel free to reopen if new details appear
