### ISSUE TITLE
[iOS] Error: ERR_COVER_OPEN

### ISSUE THREAD

**Issue by SpQuyt** [tr3v3r/react-native-esc-pos-printer#71]
I installed package and run on iOS real device **(iPhone 8 Plus - iOS 15.1)**
My printer is **TM-m30II-H_003805**

I initialized and connected successfully to printer.
But when I use function **send**, it returns ERR_COVER_OPEN.

Below is my code + error
<img width="638" alt="image" src="https://user-images.githubusercontent.com/17812909/191921291-2772acf2-d04b-4f39-895d-5d24c1108b44.png">
<img width="515" alt="image" src="https://user-images.githubusercontent.com/17812909/191921382-90307c8b-6f6b-4c8f-b665-bc59542efe63.png">

Do you have any idea to fix this bug?
Thank you!

**Comment by tr3v3r** [comment]
@SpQuyt possibly you didn't close the cover for a paper on your printer?

**Comment by SpQuyt** [comment]
> @SpQuyt possibly you didn't close the cover for a paper on your printer?

Ah my bad. This is the 1st time I use this kind of printer. 
After closing cover, I can print now.
Thank you very much for your quick reply! @tr3v3r
