### ISSUE TITLE
Not working on android 12

### ISSUE THREAD

**Issue by hasan-py** [tr3v3r/react-native-esc-pos-printer#73]
Print working fine under 12 os in android. But os 12 not working. Showing this error: 

Need android.permission.BLUETOOT H_CONNECT permission for android .contentAttributionSource@b5c1a3c4: AdapterService getBondedDevices

**Comment by tr3v3r** [comment]
@hasan-py Hi!
Did you add all permissions according to the docs? 

https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/INSTALLATION.md#android-rn--060

**Comment by hasan-py** [comment]
Yes. I have done all permissions according to the docs.

**Comment by tr3v3r** [comment]
@hasan-py  I see that we need to update the native SDK to support Android 12. I'll prepare new release soon

**Comment by hasan-py** [comment]
Thanks a lot.

**Comment by tr3v3r** [comment]
@hasan-py 
Just release v2.2.0.
SDK updated to v.2.22.0. Android 12 support added.

[Installation docs](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/INSTALLATION.md) updated

**Comment by hasan-py** [comment]
Thank you so much!
