### ISSUE TITLE
Make this library compatible with Expo and EAS + dev client

### ISSUE THREAD

**Issue by 0ctanium** [tr3v3r/react-native-esc-pos-printer#74]
Adding expo module autolinking and a config plugin would be great for expo and RN (with expo tools) users in order to simplify the package installation.

I link here the documentation to expo module to automatically instal the SDK: https://docs.expo.dev/bare/installing-expo-modules/
And to automatically update the Info.plist / AndroidManifest.xml with correct metadata: https://docs.expo.dev/guides/config-plugins/

**Comment by 0ctanium** [comment]
You will soon here from me with a PR containing the needed development ;)

**Comment by tr3v3r** [comment]
> You will soon here from me with a PR containing the needed development ;)

Wow that will be amazing!) looking forward to hearing from you

**Comment by feiwu77777** [comment]
Hello, please let me know when the PR will be ready, I'm very interested to use it for my expo project!

**Comment by tr3v3r** [comment]
@feiwu77777 @0ctanium I've investigated and realized that to run this lib using Expo no additional changes required from our side. Everything is on Expo side:
1) expo cli + expo-dev-client + EAS cloud build or local build of custom Expo Go app.

This is a good short video that explains everything: https://www.youtube.com/watch?v=Iw8FAUftJFU
These are videos with step-by-step tutorial:
https://www.youtube.com/watch?v=id0Im72UN6w
https://www.youtube.com/watch?v=sHRgQjxNj5E&t=307s
https://www.youtube.com/watch?v=YjJ0NG9MFkg

**Comment by tr3v3r** [comment]
https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/EXPO.md

**Comment by TrustyTechSG** [comment]
Im facing build error when adding this project for Expo EAS build, anyone have the same issue?

❌  error: Multiple commands produce '/Users/expo/Library/Developer/Xcode/DerivedData/ProjectName-cafzucgbgydnbsdfsuflhvailugi/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/react_native_esc_pos_printer.framework/Headers/ePOS2.h'

**Comment by TrustyTechSG** [comment]
> @TrustyTechSG Hi, I've tested the expo dev client (locally) on iOS with this lib, and everything was OK. Could you please share a reproducible repo?

Hi @tr3v3r , thank you for the quick reply, and I managed to made a minimum reproducible demo here 
https://github.com/tr3v3r/react-native-esc-pos-printer/issues/74#issuecomment-1328779355

Looks like it cause by expo-build-properties plugin useFrameworks: "static". Not sure where goes wrong.

**Comment by M-Mazen** [comment]
> 

Could you share reop expo app with lib 
Or upload video

**Comment by TrustyTechSG** [comment]
Hi @M-Mazen, this is a build error during fastlane, no App generated, you can clone my reproducible repo above and run command eas build --platform ios, then you will see the error in your Expo cloud console.

**Comment by kiyohken2000** [comment]
Indeed, if I set `expo-build-properties` in `app.json`, I get the following error.

**app.json**

```
"plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 33,
          },
          "ios": {
            "useFrameworks": "static",
            "deploymentTarget": "13.0"
          },
        },
      ]
    ]
```

**getting error**

```
error: Multiple commands produce '/Users/expo/Library/Developer/Xcode/DerivedData/escposprintertest-aqljnukaytvhhvcamunukwmgjpef/Build/Intermediates.noindex/ArchiveIntermediates/escposprintertest/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/react_native_esc_pos_printer.framework/Headers/ePOS2.h'
```

Remove `expo-build-properties` from `app.json` and build succeeds.

my repo
https://github.com/kiyohken2000/esc-pos-printer-test

**Comment by tolypash** [comment]
So after more investigation, and sorry for double posting I found out that I need the `expo-build-properties` because of react native firebase requiring `useFrameworks: static`

```
"plugins": [
      "@react-native-firebase/app",
      "@react-native-firebase/perf",
      "@react-native-firebase/crashlytics",
      "expo-build-properties"
    ],
```

Is there any way to make it work with expo-build-properties? I previously ran `expo prebuild` so maybe I can make some changes to the pod file?

**Comment by tolypash** [comment]
Alright so I can confirm this is an iOS only issue - on Android it works and builds fine.

I can continue my development for now, but I'll need to find a fix for iOS. If anyone has any idea, please let's try it 🙏 

(P.S. sorry for triple posting 😛 )

**Comment by tr3v3r** [comment]
@tolypash I've just created a new expo project and run the build locally with the latest lib version and for me it's OK:

```bash
expo init test
```

```bash
cd test && expo install react-native-esc-posprinter
```

```bash
yarn add expo-dev-client
```

```bash
expo run:ios
```
Have I missed anything?

**Comment by tr3v3r** [comment]
@tolypash @TrustyTechSG release a new version (2.5.1) that removes this dublicate issue:

<img width="900" alt="image" src="https://user-images.githubusercontent.com/23724142/227803705-221dbf97-25f2-4f99-9411-467d4abc2b60.png">

Could you please try it on?

**Comment by tolypash** [comment]
@tr3v3r Thank you so much 🙏
I will test it out shortly and let you know

**Comment by tolypash** [comment]
<img width="1198" alt="Screenshot 2023-03-27 at 1 20 27 AM" src="https://user-images.githubusercontent.com/22174779/227808247-a54d7cfc-2d27-45b5-9c70-0945fde0b472.png">

Build successful! ✅ 

@tr3v3r Thanks a lot for your work! 😁

**Comment by tr3v3r** [comment]
Happy to see it ! 🎉
No
