### ISSUE TITLE
Error building project with CompileSDK 31 and react 0.70.3

### ISSUE THREAD

**Issue by hishammalik** [tr3v3r/react-native-esc-pos-printer#75]
Getting error as below:

```
> Task :app:compressReleaseAssets
Execution optimizations have been disabled for task ':app:compressReleaseAssets' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/arkhitech/projects/arkhitech/howmuch/howmuch-pos-native/android/app/build/intermediates/assets/release/mergeReleaseAssets'. Reason: Task ':app:compressReleaseAssets' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :react-native-esc-pos-printer:verifyReleaseResources FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-esc-pos-printer:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/arkhitech/projects/arkhitech/howmuch/howmuch-pos-native/node_modules/react-native-esc-pos-printer/android/build/intermediates/merged_res/release/values/values.xml:2749: AAPT: error: resource android:attr/lStar not found.
```

tried adding different versions of androids.core and appcompat as per some solutions found on google, but nothing seems to work.
```
    implementation "androidx.appcompat:appcompat:1.2.0"
    implementation "androidx.core:core:1.7.0"    
    implementation "androidx.core:core-ktx:1.7.0"
```

Any help would be greatly appreciated.

**Comment by tr3v3r** [comment]
@hishammalik  it seems we need to update the native SDK. I'll prepare new release soon

**Comment by tr3v3r** [comment]
Just release v2.2.0.
SDK updated to v.2.22.0. Android 12 support added.

**Comment by hishammalik** [comment]
thank you for your efforts @tr3v3r

**Comment by hishammalik** [comment]
@tr3v3r unfortunately the error remains even with the upgrade. Still getting the error as below when creating release:

`
> Task :react-native-esc-pos-printer:verifyReleaseResources FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-esc-pos-printer:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/arkhitech/projects/arkhitech/howmuch/howmuch-pos-native/node_modules/react-native-esc-pos-printer/android/build/intermediates/merged_res/release/values/values.xml:2749: AAPT: error: resource android:attr/lStar not found.
`

**Comment by tr3v3r** [comment]
@hishammalik I've tested on the example folder. Probably RN version is the reason. I'll try to update to the latest soon
Thanks

**Comment by hishammalik** [comment]
@tr3v3r the app in example folder is set to CompileSDK 30 and gradle 4.2.1. Not seeing those as updated in the latest commit. grade 4.2.1 does not support java 11 either which requires minimum 5.1.1. However, react-native-gradle-plugin has bumped gradle 7.5.1

Hope this helps in setting up environment to reproduce the error.

**Comment by tr3v3r** [comment]
@hishammalik  just release v2.2.1. I've tested so should be ok now. 
Could please verify from your side?
