### ISSUE TITLE
Works on all Bluetooth thermal printers?

### ISSUE THREAD

**Issue by LouisMuriuki** [tr3v3r/react-native-esc-pos-printer#76]
Hello i was wondering if this lib will work on all printers or is it printer specific

**Comment by tr3v3r** [comment]
@LouisMuriuki  Since this library is a wrapper of SDK provided by EPSONm it supports only EPSON thermal printers.
Here is the full list of currently supported models:
https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/and2200.pdf

**Comment by JulianKingman** [comment]
Couldn't this library support more models that use the esc/pos protocol, if it didn't filter them?

**Comment by tolypash** [comment]
@JulianKingman I also have the same question @tr3v3r
