### ISSUE TITLE
Epson TM-T20III printer setup

### ISSUE THREAD

**Issue by feiwu77777** [tr3v3r/react-native-esc-pos-printer#77]
I just bought an Epson TM-T20III, I followed all the installation steps and just turned on the printer without any other cable connection. I tried to to detect the printer with EscPosPrinter.discover() or EscPosPrinter.pairingBluetoothPrinter() but it doesn't work. Does this printer have bluetooth or should I do some setup with the printer itself (like connecting it to my wifi) ?

**Comment by tr3v3r** [comment]
Hi @feiwu77777.

I have printer TM-T20II (LAN connection) and for me, the initial setup was something like this:
1) Connect the printer to your PC with a LAN cable and assign a new IP address for the printer. Video that might help (for LAN) https://www.youtube.com/watch?v=zyoJXmede94&t=224s
2) Connect the printer to the router and on a device with connect to the same network trying to discover

Also, you might need to change **the connection interface** of the printer.
Related video https://www.youtube.com/watch?v=OHP8WquAcyg

For Bluetooth actually, as I know you first need to connect the printer to your device ( as a regular Bluetooth device ) and then discover. Don't forget to complete all the steps in the instructions for the Bluetooth connection
Android
<img width="733" alt="image" src="https://user-images.githubusercontent.com/23724142/200689774-4bbb2178-ab2c-42ef-a514-a1877a0ba397.png">
IOS
<img width="938" alt="image" src="https://user-images.githubusercontent.com/23724142/200689699-a84e0f7e-9962-4bad-8ff7-57ff9d35c1b2.png">

Hope this helps.

**Comment by tr3v3r** [comment]
@feiwu77777 Please let me know if it helps or if you find another tutorial ;) I'd like to share it with the community

**Comment by tr3v3r** [comment]
@feiwu77777  Thanks for the explanation! Yes, I'll think about these docs and how to organize them better. I also was in the same situation when just bought a printer.

And from experience LAN connection is the most stable one so it's a good choice from your side.
