### ISSUE TITLE
Cannot find any printer on Kiosk device!!

### ISSUE THREAD

**Issue by nvdnvd00** [tr3v3r/react-native-esc-pos-printer#78]
Hi, I'm intergrating the library for a kiosk device with printer connected via USB port
![image](https://user-images.githubusercontent.com/17423070/203017697-12c747d5-26b0-48ec-864c-d26cacf9efed.png)
My app working okay with my tablet but It couldn't find any printer on kiosk
![image](https://user-images.githubusercontent.com/17423070/203018098-d86377a3-dbd8-4e76-b05b-72d2cc73b7f9.png)

Didn't return any error, it's just discover forever.

I tried again with other app: TM Assistant and it can detect my printer normally
![image](https://user-images.githubusercontent.com/17423070/203018362-8fd6d81f-8602-4dee-97cc-a873083e489e.png)
My printer is EU-m30

Do you know why? May I missed some configuration from android native ? 

Kiosk found new USB device in android logcat:
```11-18 09:38:50.218     0     0 I usb 5-1.2: New USB device found, idVendor=04b8, idProduct=0e2e, bcdDevice= 1.00
11-18 09:38:50.218     0     0 I usb 5-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
11-18 09:38:50.218     0     0 I usb 5-1.2: Product: EU-m30
11-18 09:38:50.218     0     0 I usb 5-1.2: Manufacturer: EPSON
11-18 09:38:50.218     0     0 I usb 5-1.2: SerialNumber: <hidden>
11-18 09:38:50.223     0     0 I usblp 5-1.2: 1.0: usblp0: USB Bidirectional printer dev 4 if 0 alt 0 proto 2 vid 0x04B8 pid 0x0E2E```

**Comment by tr3v3r** [comment]
@nvdnvd00  Hello!
Have you tried to run an [example](https://github.com/tr3v3r/react-native-esc-pos-printer/tree/main/example) app?
Could you please try to look at a logcat during "discovery"?

**Comment by nvdnvd00** [comment]
@tr3v3r  Yes, my app working perfectly on my tablet. But it discover forever on kiosk device 
<img width="324" alt="CleanShot 2022-11-21 at 18 04 21@2x" src="https://user-images.githubusercontent.com/17423070/203034846-e962fffe-4d5d-4c01-b3f8-d5f8c92e6c23.png">
I'll put logcat file (of kiosk device) here if you need it
https://www.dropbox.com/sh/q6310jkd50wecim/AADwrS7nuhw6JoEYh6jMJX6xa?dl=0&preview=2022.11.17_logcat.txt

**Comment by tr3v3r** [comment]
Could you tell me a bit more info about your kiosk device?
Android version
And processor architecture?
[processor architecture](https://stackoverflow.com/questions/11989629/api-call-to-get-processor-architecture)

**Comment by tr3v3r** [comment]
@nvdnvd00  Btw how did you achieve such a layout? I mean text on the left and right?
<img width="220" alt="image" src="https://user-images.githubusercontent.com/23724142/203059048-0b4b5105-c4e4-4aac-822e-9476705c0cee.png">

asking because working right now on the way to do it

**Comment by nvdnvd00** [comment]
@tr3v3r  I  repeat "space"  between left side and right side. It still works for long line with wrap.
I'm waiting for kiosk information and send it soon
```
const printLeftRight = (
	printing: Printing,
	left: string,
	right: string,
	maxChar: number,
	size: TScalingFactors = 1,
) => {
	const totaLeft: number = left.length * size;
	const totaRight: number = right.length * size;
	const totalChar: number = totaLeft + totaRight;
	let centerSpaceLength: number = 0;
	let numberOfLines = 1;

	while (numberOfLines * maxChar < totalChar) {
		numberOfLines++;
	}

	centerSpaceLength = numberOfLines * maxChar - totalChar;

	printing
		.size(size)
		.text(left)
		.size(1)
		.text(' '.repeat(centerSpaceLength))
		.size(size)
		.text(right)
		.newline();
};
```

**Comment by tr3v3r** [comment]
@nvdnvd00  and for **maxChar** you're using this method, right?
<img width="544" alt="image" src="https://user-images.githubusercontent.com/23724142/203065148-c4f53e81-b66d-40d6-a66d-8648646e65fc.png">

**Comment by nvdnvd00** [comment]
@tr3v3r  Correct!

**Comment by nvdnvd00** [comment]
@tr3v3r  Here's kiosk device specs (highlight part)
<img width="1089" alt="CleanShot 2022-11-21 at 22 40 45@2x" src="https://user-images.githubusercontent.com/17423070/203096475-38f064f4-b9e5-42e0-9bda-df2c87a7188f.png">

**Comment by tr3v3r** [comment]
@nvdnvd00 sorry but I need also processor architecture.

**Comment by tr3v3r** [comment]
Sorry I see x86 my fault

**Comment by tr3v3r** [comment]
@nvdnvd00 Ok!
Since your application works on tablets I suppose this is not a problem with the library for USB connections.
What I can do:  I'll add support for x86_64 arch for Android (which is missed right now) in an upcoming release ( I'll try to do it today ). 

From your side: Please try to find what exactly happens when you try to discover on the Android side. Any errors/logs why you can not see the device Also double check if all permissions are added according to docs.

Also if it possible try to connect printer with other connection type (Bluetooth, LAN )

**Comment by jankoJelic** [comment]
Hello, I can also not discover serial printer with "discover" on kiosk. I get empty array back as a response. Do you have any tips for those?

**Comment by tr3v3r** [comment]
@jankoJelic  just released 2.3.0. 
Add support of x86_64 arch please try if it helps.

**Comment by jankoJelic** [comment]
Nah, still an empty array
Code:
```
 useEffect(() => {
    const test = async () => {
      const printers = await EscPosPrinter.discover();
      console.log(printers);
    };

    test();
  }, []);
```
Logs:
 LOG  requestAndroidPermissions true
 LOG  enableLocationSetting true
 LOG  []

**Comment by jankoJelic** [comment]
I may have solved mine and maybe someone else's problem. I could find and print with this library in this case:
https://github.com/melihyarikkaya/react-native-serialport/

It might help you with improving your project. 

I will try using serialport's port opening and your API for printing (which is great btw, nice job!) and let you know how it works

**Comment by tr3v3r** [comment]
> Nah, still an empty array Code:
> 
> ```
>  useEffect(() => {
>     const test = async () => {
>       const printers = await EscPosPrinter.discover();
>       console.log(printers);
>     };
> 
>     test();
>   }, []);
> ```
> 
> Logs: LOG requestAndroidPermissions true LOG enableLocationSetting true LOG []

Can I ask you to send me a logs from Android Studio logcat when you run discover method?

**Comment by Rehankhalil462** [comment]
@tr3v3r  after executing the following code ,
  try {
        const printers = await EscPosPrinter.discover();
        console.log("printers", printers);
      } catch (error) {
        console.log("Error:", error);
      }

getting the following console errors

requestAndroidPermissions false
Error: No permissions granted

I am using Expo React Native in Dev Client. and added these   "permissions": [
     "android.permission.BLUETOOTH",
     "android.permission.BLUETOOTH_ADMIN",
    "android.permission.BLUETOOTH_CONNECT",
     "android.permission.BLUETOOTH_SCAN",
  "android.permission.INTERNET",
     "android.permission.WRITE_EXTERNAL_STORAGE",
    "android.permission.READ_EXTERNAL_STORAGE",
     "android.permission.ACCESS_COARSE_LOCATION"
   ],

in app.json file. 

Even if I request BLUETOOTH_CONNECT and BLUETOOTH_SCAN permissions using PermissionsAndroid from react native it is giving this response {"android.permission.BLUETOOTH_CONNECT": "never_ask_again", "android.permission.BLUETOOTH_SCAN": "never_ask_again"}.

can you please check what is the issue ?

**Comment by tr3v3r** [comment]
According to [official docs](https://download.epson-biz.com/modules/pos/index.php?page=single_soft&cid=7424&scat=61&pcat=3) of the Android SDK: 

<img width="375" alt="image" src="https://github.com/tr3v3r/react-native-esc-pos-printer/assets/23724142/ae9fcc44-957c-4b25-9730-447b0d770739">

**Comment by tr3v3r** [comment]
@tolypash  you can try at least

**Comment by tolypash** [comment]
[test.log](https://github.com/tr3v3r/react-native-esc-pos-printer/files/13441378/sally.log)

Here it is, any help is much appreciated. I also tried your new version, with the class based approach but it seems like it just gets stuck and doesn’t resolve the promise at all of discovering

**Comment by tr3v3r** [comment]
@tolypash  I can't see any related to printer SDK in these logs.

Have you checked if the app has all the necessary permissions?

**Comment by tolypash** [comment]
We’re trying to get Bluetooth working. 

Yes, I realised that about the new discovery API, but then again it still awaits on it and it doesn’t fire the event listener (meanwhile it does on iOS)

For Android I have Bluetooth permission on, we pair the printer in settings and then turn on the app. Also access location we have. Anything else I might be missing?

Also, this issue is specific on a special Android device for payments which doesn’t have Google play on it. Could this be an issue with location services? 🤔

**Comment by tr3v3r** [comment]
@tolypash  it could be the reason yes 
Have you tried to log what this function returns for your case?
https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/src/core/utils/permissions.ts

They both should give -> true

**Comment by tolypash** [comment]
Okay thank you I will try those and get back to you 🙏

**Comment by tolypash** [comment]
@tr3v3r Thank you so much!! 🙏  That was the issue, the google services! I assume @nvdnvd00 had the same issue :)

**Comment by tr3v3r** [comment]
@tolypash happy to hear that!

 If you're using version 3.0.1 I can create a fix for you, to make this permission check optional

**Comment by tolypash** [comment]
@tr3v3r Currently I have it patched for now, but if that will be possible will great, so I can also change it for devices that won't have Google services on them, by parameter 🙏

**Comment by tr3v3r** [comment]
I added a code to the Android code to skip checking if Google services are unavailable.

Here it is:
https://github.com/tr3v3r/react-native-esc-pos-printer/releases/tag/vv3.0.2
