### ISSUE TITLE
Error: ERR_PARAM at example print

### ISSUE THREAD

**Issue by jankoJelic** [tr3v3r/react-native-esc-pos-printer#79]
Hello, I have installed your library and when I run code from the example:
```
const printing = new EscPosPrinter.printing();

const status = await printing
        .initialize()
        .align('center')
        .line('DUDE!')
        .newline()
        .cut();
        
      console.log(JSON.stringify(status));
```

log output:
`{"_buffer":[[4,[1]],[0,["DUDE!"]],[1,[1]],[1,[1]],[7,[]]],"_state":{"bold":false,"underline":false,"smooth":false},"_currentFontWidth":1}`

when I append .send() to the end I get this:
Possible Unhandled Promise Rejection (id: 3):
Error: ERR_PARAM
Error: ERR_PARAM

Any tips on this one? Have you encountered this problem?

**Comment by beinmedia-tech** [comment]
same issue

**Comment by tousif-p99soft** [comment]
Any update on this?

**Comment by marab2** [comment]
https://github.com/tr3v3r/react-native-esc-pos-printer/issues/104#issuecomment-1824901357
Solution here but for iOS for now only.

**Comment by tr3v3r** [comment]
Please check version 4.0.0
