### ISSUE TITLE
Can't init printer using instantiate

### ISSUE THREAD

**Issue by drozddamian** [tr3v3r/react-native-esc-pos-printer#81]
I'm trying to use multiple printers in one app.
Using `init` method and `disconnect` after successful printout works fine, but `init` method takes too much time.

I've decided to use [zustand](https://github.com/pmndrs/zustand) and store there initialized printing service but I think this **printing** uses singleton since the next one overwrites first one...

I've seen `instantiate` method in API, but when I try to use it instead of `init` it fails with **error code 2** - did some digging but didn't find anything helpful... Payload seems to be the same as in init method which works 😢

**Comment by marceloch2** [comment]
I have the same, trying for days to print in multiple printers, but no luck yet. Your point to the Singleton patter existing makes sense, going to check the source code too.

**Comment by drozddamian** [comment]
@marceloch2 I found out I'm not using the latest lib version. Just upgrade it to the latest version and remember to pass **target** to **send** method ✌🏻

**Comment by drozddamian** [comment]
Works fine on v.2.3.0 ✅
