### ISSUE TITLE
iOS: Module ThePrinterWrapper requires main queue setup error

### ISSUE THREAD

**Issue by sisoalbert** [tr3v3r/react-native-esc-pos-printer#84]
I am getting this error on iOS: Module ThePrinterWrapper requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`.

**Comment by Rehankhalil462** [comment]
@sisoalbert  yes i am getting the same. did you manage to find the solution?

**Comment by HalimaHanafy-ZID** [comment]
@tr3v3r hi, I'm also facing the same warning and couldn't get the app working with flipper open 
<img width="581" alt="Screenshot 2023-02-15 at 7 59 23 AM" src="https://user-images.githubusercontent.com/121756432/218945270-83de6813-6de3-46ba-a7fa-a63bcd1ae3d3.png">

    "react-native-esc-pos-printer": "^2.3.0",
    "react-native": "^0.70.6",
and run the example..
here is the solution , if you could check plz:
https://reactnative.dev/docs/0.61/native-modules-ios#implementing--requiresmainqueuesetup

**Comment by Rehankhalil462** [comment]
> @Rehankhalil462 @sisoalbert could you please expand on it please? It would be great to have a reproducible demo or at least a bit more details. (steps, code snipped, lin and OS version, react-native or expo and etc.)

I am using following configuration
expo : sdk 46
react-native : 0.69.6
react : 18.0.0

and using expo development build for app to run in Expo GO.

Testing Environment 
Android Device : Samsung Galaxy J7 Pro
Ios Device : Iphone 11

**Comment by tolypash** [comment]
@tr3v3r Hey, I have the same warning. Doesn't cause any issues, I can print but it always shows up on launch of the app.

**Comment by Hyperman012** [comment]
@tr3v3r  I'm seeing this error in trying to get my RN code to work. I think it may be related to the issue I'm seeing. if i put the code to print directly tied to a button press it seems to work. However, when I seem to execute the code in an asynchronous manner I get a "ERR_CONNECT" message and it doesn't print.
