### ISSUE TITLE
print array of object

### ISSUE THREAD

**Issue by HalimaHanafy-ZID** [tr3v3r/react-native-esc-pos-printer#87]
Hi, is it possible to print an array of object?

**Comment by tr3v3r** [comment]
Hi @HalimaHanafy-ZID
What do you mean by "object"?
If you want to print simultaneously you cab try [this](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/API.md#instantiate-target-seriesname-language-) 

and here is an example 
https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/example/src/MultiPrint.tsx

**Comment by NabilBenOun1** [comment]
Hi @tr3v3r 

data method is not working and there are no examples mentioned in your documentation for the printer.data() method.
