### ISSUE TITLE
base64 string image print quality is bad

### ISSUE THREAD

**Issue by Rehankhalil462** [tr3v3r/react-native-esc-pos-printer#89]
I am using epson tm-p20 . i am getting base64 string of an image from the server and printing with the following function 

```javascript
 .image(
            { uri: param },
            { width: 384 }
          )
```
but getting a poor quality image printing. Meanwhile if i print the same base64 image with a Sunmi Printer Device it is clear and ok. 
384 width is the maximum width of the image and it is the at most we can specify in the image method. I tried with 400 width it is not working. 

how can i improve the quality of printing an image? is there any specific configuration for the base64 printing images?

**Comment by tr3v3r** [comment]
@Rehankhalil462  could share the image here.
Also please give please more details. At least Platform and code snippet

**Comment by smilank3** [comment]
``` javascript
 .image({ uri: `data:image/png;base64,${.....data...}` }, {
        width: 530,
        color: 'EPOS2_COLOR_4',
        mode: 'EPOS2_MODE_GRAY16',
        halftone: 'EPOS2_HALFTONE_THRESHOLD',
        brightness: 0.3
      })```

The above worked for me.
