### ISSUE TITLE
discover multiple printers

### ISSUE THREAD

**Issue by Rehankhalil462** [tr3v3r/react-native-esc-pos-printer#90]
i am using this code in my application 
```javascript 
   try {
      EscPosPrinter.discover().then((printers) => {
        console.log("PRINTERS!", printers);
        setPrinters(printers);
      });
    } catch (error) {
console.log(error.message)
}
```

but it is showing only 1 printer which i found earlier. 
Now I turned on 3 more epson printers but it is still showing the older one. 
If i turn off the older one, then it is returning empty array [ ] on above discover method, even other devices are powered on.

**Comment by tr3v3r** [comment]
@Rehankhalil462 please try this
https://github.com/tr3v3r/react-native-esc-pos-printer/issues/54#issuecomment-1110858740

and the issues is duplicate

https://github.com/tr3v3r/react-native-esc-pos-printer/issues/40

**Comment by Rehankhalil462** [comment]
@tr3v3r  do i need to patch this mentioned code into the library on my side? or i can directly use this in my RN application?

**Comment by tr3v3r** [comment]
Fixed in v.3.0.0

https://github.com/tr3v3r/react-native-esc-pos-printer/releases/tag/vv3.0.0
