### ISSUE TITLE
EscPosPrinter.disconnect error

### ISSUE THREAD

**Issue by Rehankhalil462** [tr3v3r/react-native-esc-pos-printer#91]
I am trying to disconnect the connected printer by following code 

```javascript
   await EscPosPrinter.disconnectPrinter(
      device.target
    );
```

getting `Error: 4` on IOS and `Error: ERR_MEMORY` on Android. It is not disconnecting with the connected printer.

**Comment by Akyna** [comment]
Last version - 3.0.3
```
    "react": "^18.2.0",
    "react-native": "0.72.7",

```

The same on IOS.
```
Disconnect error [Error: 4]
```
