### ISSUE TITLE
error/exception messages detail??

### ISSUE THREAD

**Issue by Rehankhalil462** [tr3v3r/react-native-esc-pos-printer#92]
@tr3v3r 

Can you please share the link where to check the description/detail of the error/exception messages that we face during discovery, initialization, disconnection ? So we can look up like what exactly the issue/error is ?

like ERR_IN_USE, ERR_MEMORY, ERR_ILLEGAL etc

**Comment by tousif-p99soft** [comment]
@Rehankhalil462 Have got the solution?

**Comment by Rehankhalil462** [comment]
@tousif-p99soft No. Not yet.

**Comment by tr3v3r** [comment]
@Rehankhalil462  @tousif-p99soft  for now guys you can try to read about errors here
ios: https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/iOS_v2.23.0.pdf
android: https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/android_v2.23.0.pdf

**Comment by Rehankhalil462** [comment]
Got it !

**Comment by vcsepis** [comment]
I am having that problem.  do you have any solution?

**Comment by vcsepis** [comment]
> Got it !

I am having that problem.  do you have any solution?

**Comment by marab2** [comment]
The solution is here https://github.com/tr3v3r/react-native-esc-pos-printer/issues/104#issuecomment-1824901357 but for iOS only for now.

**Comment by tr3v3r** [comment]
Please use 4.0.0 version. It has way better error handling
