### ISSUE TITLE
data method is not working 

### ISSUE THREAD

**Issue by NabilBenOun1** [tr3v3r/react-native-esc-pos-printer#94]
Hi,
data method is not working  and there are no examples mentioned in your documentation for the printer.data() method.

**Comment by Rehankhalil462** [comment]
@NabilBenOun1  what you would like to print?

**Comment by NabilBenOun1** [comment]
@Rehankhalil462 I want to print binary data

**Comment by Rehankhalil462** [comment]
> @Rehankhalil462 I want to print binary data

Send me  the binary data that you want to print. I'll check on my side and let you know about the usecase.

**Comment by tr3v3r** [comment]
@NabilBenOun1 You can use https://www.npmjs.com/package/esc-pos-encoder to pass data to this method:

```javascript
let result = encoder
    .text('This is ')
    .bold()
    .text('bold')
    .bold()
    .encode()
```

```javascript
let result = encoder
    .raw([ 0x1c, 0x2e ])
    .encode()
```
