### ISSUE TITLE
how to clear the buffer/queue?

### ISSUE THREAD

**Issue by Rehankhalil462** [tr3v3r/react-native-esc-pos-printer#95]
If printer was not able to print due to disconnection error , then how to not let the printer print the previous image on reconnection? 
I mean how to clear the queue/ buffer on reconnection?

**Comment by ChristianKohlberg** [comment]
Same here. Printer goes wild when it is connected back to the tablet.

**Comment by tr3v3r** [comment]
Check version 4.0.0
