### ISSUE TITLE
discovering printers even after they are turned off.

### ISSUE THREAD

**Issue by Rehankhalil462** [tr3v3r/react-native-esc-pos-printer#97]
While discovering, if the printers are turned on, it is discovering all printers. 
But when printers are turned off, and when I try to discover after that, it is even discovering those printers which are turned off? why?

**Comment by tolypash** [comment]
For me this is not the case locally

**Comment by Rehankhalil462** [comment]
@tolypash pair with a printer, do some printing stuff.  Then turn that off and try to discover. It will discover those turned off devices as well.

**Comment by tolypash** [comment]
@Rehankhalil462 are you using `init` or `instantiate`?
