### ISSUE TITLE
IOS build Error

### ISSUE THREAD

**Issue by Rehankhalil462** [tr3v3r/react-native-esc-pos-printer#99]
Getting this error on building for IOS
```javascript
❌  duplicate symbol '_A' in
┌─ libRNBluetoothEscposPrinter.a(RNBluetoothEscposPrinter.o)
└─ libepos2.a(AccesscodeEngine.o)
❌  ld: 1 duplicate symbol for architecture arm64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I am using  this https://github.com/tulparyazilim/tp-react-native-bluetooth-printer library for Scanning bluetooth devices and using your library for printing receipts. 

Working fine on Android without any build error.

 IOS Build Environment 

```javascript
+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.210.0                 |
| sdk         | iPhoneOS16.0.sdk        |
+-------------+-------------------------+
```

any help? 

@andrioid @JesperBadstue @user512 @echoneet @fragilehm @tr3v3r @lufke @MinaZakaria @kamal-hossain

**Comment by Rehankhalil462** [comment]
@fragilehm  @tr3v3r any help in finding the issue please??

**Comment by tr3v3r** [comment]
@Rehankhalil462  hi I can help you if you could provide a simple reproducible demo. 

Just create bare RN project and push it to GitHub

Thanks

**Comment by Rehankhalil462** [comment]
> 

Thanks for your reply. 
I am using expo development client. I don't have mac with me. 
I will initialize a new expo project and install these libraries  so you can check simple reproducible demo and then will let you know once I push that to GitHub.

**Comment by Rehankhalil462** [comment]
@tr3v3r  here is the demo https://github.com/Rehankhalil462/react-native-demo. I just installed two printers libraries . You can create a build for ios using EAS (expo application services).
I didn't have mac so I was working on EXPO. 
Otherwise you can just install above mentioned libraries in your bare react-native project if you have mac and when you would build the application for IOS , then you would see above mentioned error.
